ci_client_web:
  stage: ci_build
  tags:
    - nodejs
  cache:
    paths:
      - nakar-client-web/node_modules/
  before_script:
    - cd nakar-client-web
    - npm ci
  script:
    - npm run build
    - npm run lint
    - npm run audit

ci_client_web_docker:
  stage: ci_build
  tags:
    - docker
  script:
    - docker build -f nakar-client-web/Dockerfile -t "nakar-client-web:dev" .
  after_script:
    - docker rmi "nakar-client-web:dev"

deploy_client_web:
  stage: build_push_docker
  only:
    - prod
  tags:
    - docker
  script:
    - IMAGE_VERSION=$(cd nakar-client-web && npm run --silent version)
    - docker build -f nakar-client-web/Dockerfile -t "git-registry.thm.de/sspp77/nakar/client-web:$IMAGE_VERSION" .
    - docker push "git-registry.thm.de/sspp77/nakar/client-web:$IMAGE_VERSION"
    - docker rmi "git-registry.thm.de/sspp77/nakar/client-web:$IMAGE_VERSION"
