nakar-db-pole:
  stage: build
  tags: 
      - ip2_mni_thm_de
  script:
    - cd nakar-db-pole
    - npm ci
    - npm run build

nakar-server:
  stage: build
  tags: 
      - ip2_mni_thm_de
  script:
    - cd nakar-server
    - npm ci
    - npm run build
    - npm run lint
    - npm run audit
    - npm run build:docker

nakar-client-web:
  stage: build
  tags: 
      - ip2_mni_thm_de
  script:
    - cd nakar-client-web
    - npm ci
    - npm run build
    - npm run lint
    - npm run audit
    - npm run build:docker
