stages:
  - ci_build
  - static_analysis
  - build_push_docker

ci_nakar-server:
  stage: ci_build
  tags:
      - nodejs
  script:
    - cd nakar-server
    - npm ci
    - npm run build

ci_nakar-client-web:
  stage: ci_build
  tags:
      - nodejs
  script:
    - cd nakar-client-web
    - npm ci
    - npm run build

static_nakar-db-pole:
  stage: static_analysis
  tags:
    - nodejs
  script:
    - cd nakar-db-pole
    - npm ci

static_nakar-server:
  stage: static_analysis
  tags:
    - nodejs
  script:
    - cd nakar-server
    - npm ci
    - npm run build:gen
    - npm run lint
    - npm run audit

static_nakar-client-web:
  stage: static_analysis
  tags:
    - nodejs
  script:
    - cd nakar-client-web
    - npm ci
    - npm run build:gen
    - npm run lint
    - npm run audit

deploy_nakar-db-pole:
  stage: build_push_docker
  only:
    - prod
  tags:
      - docker
  script:
    - cd nakar-db-pole
    - docker build -t "git-registry.thm.de/sspp77/nakar/db-pole:$(npm run --silent version)" .
    - docker push git-registry.thm.de/sspp77/nakar/db-pole:$(npm run --silent version)

deploy_nakar-server:
  stage: build_push_docker
  only:
    - prod
  tags:
      - docker
  script:
    - cd nakar-server
    - docker build -t "git-registry.thm.de/sspp77/nakar/server:$(npm run --silent version)" .
    - docker push git-registry.thm.de/sspp77/nakar/server:$(npm run --silent version)

deploy_nakar-client-web:
  stage: build_push_docker
  only:
    - prod
  tags:
      - docker
  script:
    - cd nakar-client-web
    - docker build -t "git-registry.thm.de/sspp77/nakar/client-web:$(npm run --silent version)" .
    - docker push git-registry.thm.de/sspp77/nakar/client-web:$(npm run --silent version)
