stages:
  - ci_build
  - build_push_docker
  - cleanup

ci_nakar-server:
  stage: ci_build
  tags:
      - nodejs
  before_script:
    - cd nakar-shared
    - npm ci
    - npm run build
    - cd ..
    - cd nakar-server
    - npm ci
  script:
    - npm run build:gen
    - npm run build
    - npm run lint
    - npm run audit

ci_nakar-client-web:
  stage: ci_build
  tags:
      - nodejs
  before_script:
    - cd nakar-shared
    - npm ci
    - npm run build
    - cd ..
    - cd nakar-client-web
    - npm ci
  script:
    - npm run build:gen
    - npm run build
    - npm run lint
    - npm run audit

ci_nakar-db-pole:
  stage: ci_build
  tags:
    - docker
  before_script:
    - cd nakar-db-pole
    - npm ci
  script:
    - npm run build
  after_script:
    - npm run clean

deploy_nakar-db-pole:
  stage: build_push_docker
  needs:
    - ci_nakar-db-pole
  only:
    - prod
  tags:
    - docker
  before_script:
    - cd nakar-db-pole
  script:
    - cd nakar-db-pole
    - docker build -t "git-registry.thm.de/sspp77/nakar/db-pole:$(npm run --silent version)" .
    - docker push git-registry.thm.de/sspp77/nakar/db-pole:$(npm run --silent version)

deploy_nakar-server:
  stage: build_push_docker
  needs:
    - ci_nakar-server
  only:
    - prod
  tags:
      - docker
  before_script:
    - cd nakar-shared
    - npm ci
    - npm run build
    - cd ..
    - cd nakar-server
  script:
    - docker build -t "git-registry.thm.de/sspp77/nakar/server:$(npm run --silent version)" .
    - docker push git-registry.thm.de/sspp77/nakar/server:$(npm run --silent version)

deploy_nakar-client-web:
  stage: build_push_docker
  needs:
    - ci_nakar-client-web
  only:
    - prod
  tags:
      - docker
  before_script:
    - cd nakar-shared
    - npm ci
    - npm run build
    - cd ..
    - cd nakar-client-web
  script:
    - docker build -t "git-registry.thm.de/sspp77/nakar/client-web:$(npm run --silent version)" .
    - docker push git-registry.thm.de/sspp77/nakar/client-web:$(npm run --silent version)

cleanup:
  stage: cleanup
  needs:
    - deploy_nakar-client-web
    - deploy_nakar-server
    - deploy_nakar-db-pole
  only:
    - prod
  tags:
    - docker
  script:
    - docker system prune -f