nakar-db-pole:
  stage: build
  tags: 
      - nodejs
  script:
    - cd nakar-db-pole
    - npm ci

nakar-server:
  stage: build
  tags: 
      - nodejs
  script:
    - cd nakar-server
    - npm ci
    - npm run build
    - npm run lint
    - npm run audit

nakar-client-web:
  stage: build
  tags: 
      - nodejs
  script:
    - cd nakar-client-web
    - npm ci
    - npm run build
    - npm run lint
    - npm run audit
