// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type PostAuthRequestBodyDto = {
    username: string;
    password: string;
};

export type PostAuthResponseBodyDto = {
    jwt: string;
    username: string;
};

export type GetAuthResponseBodyDto = {
    username: string;
};

export type UserPreviewDto = {
    id: string;
    displayName: string | null;
};

export type NodeConfigurationDto = {
    id: string;
    type: 'link' | 'image';
    label: string;
    property: string;
    linkTemplate: string;
    urlEncode: boolean;
};

export type DatabaseConnectionDto = {
    id: string;
    title: string;
    browserUrl: string;
    connectionUrl: string;
    database: string;
    nodeConfigurations: Array<NodeConfigurationDto>;
    databaseType: 'neo4j' | 'sparql' | 'wikidata';
};

export type StartPageProjectDto = {
    id: string;
    title: string;
    owner: UserPreviewDto | null;
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
    activeUsers: Array<UserPreviewDto>;
};

export type StartPageRoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    joinCanvasId: string;
    activeUsers: Array<UserPreviewDto>;
};

export type StartPageDto = {
    myProjects: Array<StartPageProjectDto>;
    collaborationProjects: Array<StartPageProjectDto>;
    recentRooms: Array<StartPageRoomDto>;
    publicRooms: Array<StartPageRoomDto>;
};

export type ScenarioQueryDto = {
    id: string;
    query: string;
    database: DatabaseConnectionDto | null;
    isTableQuery: boolean;
};

export type ScenarioParameterDto = {
    id: string;
    identifier: string;
    title: string;
    defaultValue: string | null;
    dataType: 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';
    allowedLabels: Array<string>;
};

export type ColorPresetDto = {
    type: 'ColorPresetDto';
    index: 0 | 1 | 2 | 3 | 4 | 5;
};

export type ScenarioPostActionDto = {
    id: string;
    type: 'none' | 'connectResultNodes' | 'compressRelationships' | 'compressNodes' | 'layout' | 'resetVisualization' | 'setGrowNodesBasedOnDegree' | 'setRelationshipClusterSize' | 'setNodeColor' | 'setNodeRadius' | 'setNodeTitleProperty' | 'setRelationshipColor' | 'setRelationshipWidth';
    label: string;
    circleRadius: number;
    layoutAlgorithm: 'forceDirected' | 'circle' | 'hierarchy' | 'none';
    relationshipType: string;
    factor: number;
    width: number;
    color: ColorPresetDto;
    radius: number;
    property: string;
};

export type ScenarioDto = {
    id: string;
    title: string | null;
    queries: Array<ScenarioQueryDto>;
    description: string | null;
    parameters: Array<ScenarioParameterDto>;
    postScenarioActions: Array<ScenarioPostActionDto>;
    postActionsDescription: Array<string>;
};

export type ScenarioGroupDto = {
    id: string;
    title: string;
    scenarios: Array<ScenarioDto>;
};

export type CanvasDto = {
    id: string;
    title: string;
};

export type RoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    canvases: Array<CanvasDto>;
    joinCanvasId: string;
    projectId: string;
    databases: Array<DatabaseConnectionDto>;
    activeUsers: Array<UserPreviewDto>;
};

export type CommonPropertyDto = {
    id: string;
    leftLabel: string;
    leftProperty: string;
    rightLabel: string;
    rightProperty: string;
    leftDatabase: DatabaseConnectionDto | null;
    rightDatabase: DatabaseConnectionDto | null;
};

export type ProjectPageDto = {
    id: string;
    title: string;
    owner: UserPreviewDto | null;
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
    scenarioGroups: Array<ScenarioGroupDto>;
    rooms: Array<RoomDto>;
    commonProperties: Array<CommonPropertyDto>;
};

export type CreateProjectRequestBodyDto = {
    title: string;
};

export type UpdateProjectRequestBodyDto = {
    title: string;
};

export type UpdateScenarioGroupRequestBodyDto = {
    title: string;
};

export type UpdateScenarioQueryEntryDto = {
    id: string;
    query: string;
    databaseId: string | null;
    isTableQuery: boolean;
};

export type UpdateScenarioQueryParameterEntryDto = {
    id: string;
    identifier: string;
    title: string;
    defaultValue: string;
    dataType: 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';
    allowedLabels: Array<string>;
};

export type UpdateScenarioPostActionColorPresetDto = {
    type: 'ColorPresetDto';
    index: 0 | 1 | 2 | 3 | 4 | 5;
};

export type UpdateScenarioPostActionEntryDto = {
    id: string;
    type: 'connectResultNodes' | 'compressRelationships' | 'compressNodes' | 'layout' | 'resetVisualization' | 'setGrowNodesBasedOnDegree' | 'setRelationshipClusterSize' | 'setNodeColor' | 'setNodeRadius' | 'setNodeTitleProperty' | 'setRelationshipColor' | 'setRelationshipWidth';
    label: string;
    circleRadius: number;
    layoutAlgorithm: 'forceDirected' | 'circle' | 'hierarchy';
    relationshipType: string;
    factor: number;
    width: number;
    color: UpdateScenarioPostActionColorPresetDto;
    radius: number;
    property: string;
};

export type UpdateScenarioRequestBodyDto = {
    title: string;
    description: string;
    queries: Array<UpdateScenarioQueryEntryDto>;
    parameters: Array<UpdateScenarioQueryParameterEntryDto>;
    postScenarioActions: Array<UpdateScenarioPostActionEntryDto>;
};

export type UpdateRoomRequestBodyDto = {
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
};

export type TestDatabaseConnectionRequestBodyDto = {
    id: string | null;
    username: string | null;
    password: string | null;
    database: string | null;
    connectionUrl: string;
    databaseType: 'neo4j' | 'sparql' | 'wikidata';
};

export type TestDatabaseConnectionResponseBodyDto = {
    success: boolean;
    message: string;
};

export type UpdateNodeConfigurationRequestBodyDto = {
    id: string;
    type: 'link' | 'image';
    label: string;
    property: string;
    linkTemplate: string;
    urlEncode: boolean;
};

export type UpdateDatabaseConnectionRequestBodyDto = {
    title: string;
    username: string | null;
    password: string | null;
    database: string;
    connectionUrl: string;
    browserUrl: string;
    credentialStoreConsent: boolean;
    databaseType: 'neo4j' | 'sparql' | 'wikidata';
    nodeConfigurations: Array<UpdateNodeConfigurationRequestBodyDto>;
};

export type UpdateCommonPropertyRequestBodyDto = {
    leftLabel: string;
    leftProperty: string;
    rightLabel: string;
    rightProperty: string;
    leftDatabaseId: string;
    rightDatabaseId: string;
};

export type ScenarioCollectionDto = {
    scenarioGroups: Array<ScenarioGroupDto>;
};

export type CanvasPageDto = {
    canvas: CanvasDto;
    scenarios: ScenarioCollectionDto;
    room: RoomDto;
};

export type PostNoteRequestBody = {
    nodeIds: Array<string>;
    content: string;
};

export type UpdateNoteRequestBodyDto = {
    content: string;
};

export type DatabaseStatsLabelDto = {
    label: string;
    exploreQuery: string;
};

export type DatabaseStatsRelationshipDto = {
    relType: string;
    exploreQuery: string;
};

export type GetDatabaseStatsResponseBodyDto = {
    relTypeCount: number | null;
    labelCount: number | null;
    relCount: number | null;
    labels: Array<DatabaseStatsLabelDto> | null;
    rels: Array<DatabaseStatsRelationshipDto> | null;
    nodeCount: number | null;
};

export type PostSearchRequestBodyDto = {
    searchTerm: string;
};

export type NodePreviewDto = {
    id: string;
    nativeId: string;
    title: string;
    labels: Array<string>;
};

export type PostSearchResponseBodyDto = {
    nodes: Array<NodePreviewDto>;
};

export type SearchCapabilitiesEntryDto = {
    label: string;
    property: string;
};

export type GetSearchCapabilitiesResponseBodyDto = {
    canExactMatchNativeId: boolean;
    canExactMatchLabel: boolean;
    exactMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
    fuzzyMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
};

export type ExpandNodePreviewEntryDto = {
    identificator: string;
    title: string;
    count: number;
};

export type ExpandNodePreviewResponseBodyDto = {
    relationships: Array<ExpandNodePreviewEntryDto>;
    labels: Array<ExpandNodePreviewEntryDto>;
};

export type ScenarioArgumentDto = {
    identifier: string;
    value: string;
};

export type LoadScenarioRequestBodyDto = {
    scenarioId: string;
    additive: boolean;
    arguments: Array<ScenarioArgumentDto>;
};

export type ExpandNodeLimitDto = {
    labels: Array<string>;
    relationships: Array<string>;
};

export type ExpandNodeRequestBodyDto = {
    nodeIds: Array<string>;
    limit: ExpandNodeLimitDto | null;
};

export type DeleteElementsRequestBodyDto = {
    nodes: Array<string>;
    edges: Array<string>;
    labels: Array<string>;
    edgeTypes: Array<string>;
};

export type UnlockNodesRequestBodyDto = {
    nodes: Array<string>;
};

export type FocusNodesRequestBodyDto = {
    nodes: Array<string>;
};

export type FocusRelationshipTypeRequestBodyDto = {
    relationshipTypes: Array<string>;
};

export type RunQueryRequestBodyDto = {
    databaseId: string;
    query: string;
    replace: boolean;
};

export type FlipCanvasRequestBodyDto = {
    axis: 'x' | 'y';
};

export type ExpandRelationshipClusterRequestBodyDto = {
    edgeIds: Array<string>;
};

export type CompressNodesRequestBodyDto = {
    label: string;
};

export type LayoutSpecificationCircleDto = {
    type: 'LayoutSpecificationCircleDto';
    radius: number;
    label: string;
};

export type LayoutSpecificationForceDirectedDto = {
    type: 'LayoutSpecificationForceDirectedDto';
    label: string;
};

export type LayoutSpecificationHierarchyDto = {
    type: 'LayoutSpecificationHierarchyDto';
    edgeType: string;
};

export type LayoutRequestBodyDto = {
    layoutSpecification: LayoutSpecificationCircleDto | LayoutSpecificationForceDirectedDto | LayoutSpecificationHierarchyDto;
};

export type ShowShortestPathRequestBodyDto = {
    nodeIds: Array<string>;
};

export type LoadNodeRequestBodyDto = {
    nativeNodeId: string;
    databaseId: string;
};

export type LiveCanvasLabelViewSettingsDto = {
    label: string;
    radius: number;
    customRadius: boolean;
    colorIndex: 0 | 1 | 2 | 3 | 4 | 5;
    titleProperty: string;
    customTitleProperty: boolean;
};

export type LiveCanvasEdgeViewSettingsDto = {
    edgeType: string;
    width: number;
    customWidth: boolean;
    colorIndex: 0 | 1 | 2 | 3 | 4 | 5;
    customColor: boolean;
};

export type LiveCanvasViewSettingsDto = {
    compressRelationshipsWidthFactor: number;
    growNodesBasedOnDegree: boolean;
    growNodesBasedOnDegreeFactor: number;
    labelSettings: Array<LiveCanvasLabelViewSettingsDto>;
    edgeSettings: Array<LiveCanvasEdgeViewSettingsDto>;
};

export type GetVersionResponseBodyDto = {
    version: string;
};

export type GetUrlResponseBodyDto = {
    url: string | null;
};

export type GrabNodeWsdto = {
    type: 'GrabNodeWsdto';
    nodeId: string;
};

export type PositionDto = {
    x: number;
    y: number;
};

export type PhysicalNodeDto = {
    id: string;
    position: PositionDto;
};

export type MoveNodesWsdto = {
    type: 'MoveNodesWsdto';
    nodes: Array<PhysicalNodeDto>;
};

export type UngrabNodeWsdto = {
    type: 'UngrabNodeWsdto';
    node: PhysicalNodeDto;
};

export type MoveCursorWsdto = {
    type: 'MoveCursorWsdto';
    position: PositionDto;
};

export type ActionWsdto = {
    action: GrabNodeWsdto | MoveNodesWsdto | UngrabNodeWsdto | MoveCursorWsdto;
};

export type CanvasChangedWsdto = {
    type: 'CanvasChangedWsdto';
    canvasId: Array<string>;
};

export type LiveCanvasMetaDataDto = {
    scenarioId: string | null;
    parameters: Array<ScenarioParameterDto>;
    arguments: Array<ScenarioArgumentDto>;
    undoAction: string | null;
    redoAction: string | null;
    users: Array<UserPreviewDto>;
};

export type ColorCustomDto = {
    type: 'ColorCustomDto';
    backgroundColor: string;
    textColor: string;
};

export type ColorDto = {
    color: ColorPresetDto | ColorCustomDto;
};

export type EdgePreviewDto = {
    type: string;
    count: number;
    percentage: number;
};

export type NoteDto = {
    id: string;
    content: string;
    nodes: Array<NodePreviewDto>;
    author: UserPreviewDto | null;
    dateTime: string;
};

export type NodeParameterizedScenarioDto = {
    id: string;
};

export type NodeParameterizedScenarioGroupDto = {
    id: string;
    scenarios: Array<NodeParameterizedScenarioDto>;
};

export type NodeDto = {
    id: string;
    nativeId: string;
    title: string;
    labels: Array<string>;
    nativeLabels: Array<string>;
    properties: {
        [key: string]: unknown;
    };
    radius: number;
    position: PositionDto;
    inDegree: number;
    outDegree: number;
    degree: number;
    namesInQuery: Array<string>;
    customColor: ColorDto | null;
    sourceTitle: string | null;
    sourceId: string;
    locked: boolean;
    isCluster: boolean;
    clusterSize: number;
    incomingEdges: Array<EdgePreviewDto>;
    outgoingEdges: Array<EdgePreviewDto>;
    creationReason: 'loadScenario' | 'expand' | 'query' | 'merge' | 'compress' | 'connectResultNodes' | 'search';
    notes: Array<NoteDto>;
    parameterizedScenarios: Array<NodeParameterizedScenarioGroupDto>;
    coverImageUrl: string | null;
    url: string | null;
};

export type EdgeDto = {
    id: string;
    nativeId: string;
    startNodeId: string;
    endNodeId: string;
    type: string;
    isLoop: boolean;
    parallelCount: number;
    parallelIndex: number;
    isCluster: boolean;
    width: number;
    properties: {
        [key: string]: unknown;
    };
    namesInQuery: Array<string>;
    sourceId: string | null;
    sourceTitle: string | null;
    clusterSize: number;
    sourceNode: NodePreviewDto;
    targetNode: NodePreviewDto;
    creationReason: 'loadScenario' | 'expand' | 'query' | 'merge' | 'compress' | 'connectResultNodes' | 'search';
    customColor: ColorDto | null;
};

export type LabelDto = {
    label: string;
    color: ColorDto;
    count: number;
    sources: Array<string>;
};

export type LiveCanvasGraphElementsDto = {
    nodes: Array<NodeDto>;
    edges: Array<EdgeDto>;
    labels: Array<LabelDto>;
};

export type LiveCanvasTableDataDto = {
    data: Array<{
        [key: string]: unknown;
    }>;
};

export type HistogramValueEntryDto = {
    value: string;
    count: number;
    percentage: number;
};

export type HistogramPropertyEntryDto = {
    key: string;
    values: Array<HistogramValueEntryDto>;
};

export type HistogramNodeEntryDto = {
    id: string;
    title: string;
    labels: Array<string>;
    degree: number;
    percentage: number;
    customColor: ColorDto | null;
};

export type HistogramDto = {
    nodeLabels: Array<HistogramValueEntryDto>;
    nodeProperties: Array<HistogramPropertyEntryDto>;
    edgeTypes: Array<HistogramValueEntryDto>;
    edgeProperties: Array<HistogramPropertyEntryDto>;
    nodes: Array<HistogramNodeEntryDto>;
};

export type LiveCanvasDataDto = {
    metaData: LiveCanvasMetaDataDto;
    elements: LiveCanvasGraphElementsDto;
    table: LiveCanvasTableDataDto;
    viewSettings: LiveCanvasViewSettingsDto;
    histogram: HistogramDto;
    notes: Array<NoteDto>;
};

export type CanvasDataReadyWsdto = {
    type: 'CanvasDataReadyWsdto';
    data: LiveCanvasDataDto;
};

export type ClearProgressWsdto = {
    type: 'ClearProgressWsdto';
};

export type CanvasElementsChangedWsdto = {
    type: 'CanvasElementsChangedWsdto';
    elements: LiveCanvasGraphElementsDto;
};

export type CanvasMetaDataChangedWsdto = {
    type: 'CanvasMetaDataChangedWsdto';
    metaData: LiveCanvasMetaDataDto;
};

export type CanvasTableDataChangedWsdto = {
    type: 'CanvasTableDataChangedWsdto';
    table: LiveCanvasTableDataDto;
};

export type CanvasHistogramChangedWsdto = {
    type: 'CanvasHistogramChangedWsdto';
    histogram: HistogramDto;
};

export type CanvasNotesChangedWsdto = {
    type: 'CanvasNotesChangedWsdto';
    notes: Array<NoteDto>;
};

export type KickWsdto = {
    type: 'KickWsdto';
};

export type PhysicsPerformanceDto = {
    performance: 'good' | 'bad';
    loadPercent: number;
    tickDuration: number;
    tickCount: number;
};

export type NodesMovedWsdto = {
    type: 'NodesMovedWsdto';
    nodes: Array<PhysicalNodeDto>;
    date: string;
    performance: PhysicsPerformanceDto;
};

export type NotificationDataDto = {
    message: string;
    severity: 'error' | 'message' | 'warning';
    date: string;
};

export type NotificationWsdto = {
    type: 'NotificationWsdto';
    notification: NotificationDataDto;
};

export type ProgressWsdto = {
    type: 'ProgressWsdto';
    progress: number | null;
    message: string;
};

export type NodeLockCollectionEntryDto = {
    id: string;
    locked: boolean;
};

export type SetNodeLocksWsdto = {
    type: 'SetNodeLocksWsdto';
    locks: Array<NodeLockCollectionEntryDto>;
};

export type CanvasViewSettingsChangedWsdto = {
    type: 'CanvasViewSettingsChangedWsdto';
    viewSettings: LiveCanvasViewSettingsDto;
};

export type CursorMovedWsdto = {
    type: 'CursorMovedWsdto';
    position: PositionDto;
    socketId: string;
};

export type EventWsdto = {
    event: CanvasChangedWsdto | CanvasDataReadyWsdto | ClearProgressWsdto | CanvasElementsChangedWsdto | CanvasMetaDataChangedWsdto | CanvasTableDataChangedWsdto | CanvasHistogramChangedWsdto | CanvasNotesChangedWsdto | KickWsdto | NodesMovedWsdto | NotificationWsdto | ProgressWsdto | SetNodeLocksWsdto | CanvasViewSettingsChangedWsdto | CursorMovedWsdto;
};

export type AuthWsdto = {
    jwt: string;
    canvasId: string;
};

export type AuthControllerGetAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth';
};

export type AuthControllerGetAuthResponses = {
    default: GetAuthResponseBodyDto;
};

export type AuthControllerGetAuthResponse = AuthControllerGetAuthResponses[keyof AuthControllerGetAuthResponses];

export type AuthControllerPostAuthData = {
    body: PostAuthRequestBodyDto;
    path?: never;
    query?: never;
    url: '/api/auth';
};

export type AuthControllerPostAuthResponses = {
    default: PostAuthResponseBodyDto;
};

export type AuthControllerPostAuthResponse = AuthControllerPostAuthResponses[keyof AuthControllerPostAuthResponses];

export type StartControllerGetStartData = {
    body?: never;
    path?: never;
    query: {
        recentRoomIds: string | null;
    };
    url: '/api';
};

export type StartControllerGetStartResponses = {
    default: StartPageDto;
};

export type StartControllerGetStartResponse = StartControllerGetStartResponses[keyof StartControllerGetStartResponses];

export type ProjectControllerDeleteProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}';
};

export type ProjectControllerDeleteProjectResponses = {
    200: unknown;
};

export type ProjectControllerGetProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}';
};

export type ProjectControllerGetProjectResponses = {
    default: ProjectPageDto;
};

export type ProjectControllerGetProjectResponse = ProjectControllerGetProjectResponses[keyof ProjectControllerGetProjectResponses];

export type ProjectControllerUpdateProjectData = {
    body: UpdateProjectRequestBodyDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}';
};

export type ProjectControllerUpdateProjectResponses = {
    default: ProjectPageDto;
};

export type ProjectControllerUpdateProjectResponse = ProjectControllerUpdateProjectResponses[keyof ProjectControllerUpdateProjectResponses];

export type ProjectControllerCreateProjectData = {
    body: CreateProjectRequestBodyDto;
    path?: never;
    query?: never;
    url: '/api/project';
};

export type ProjectControllerCreateProjectResponses = {
    default: ProjectPageDto;
};

export type ProjectControllerCreateProjectResponse = ProjectControllerCreateProjectResponses[keyof ProjectControllerCreateProjectResponses];

export type ScenarioGroupControllerCreateScenarioGroupData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/scenario-group';
};

export type ScenarioGroupControllerCreateScenarioGroupResponses = {
    default: ScenarioGroupDto;
};

export type ScenarioGroupControllerCreateScenarioGroupResponse = ScenarioGroupControllerCreateScenarioGroupResponses[keyof ScenarioGroupControllerCreateScenarioGroupResponses];

export type ScenarioGroupControllerDeleteScenarioGroupData = {
    body?: never;
    path: {
        scenarioGroupId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/scenario-group/{scenarioGroupId}';
};

export type ScenarioGroupControllerDeleteScenarioGroupResponses = {
    200: unknown;
};

export type ScenarioGroupControllerUpdateScenarioGroupData = {
    body: UpdateScenarioGroupRequestBodyDto;
    path: {
        scenarioGroupId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/scenario-group/{scenarioGroupId}';
};

export type ScenarioGroupControllerUpdateScenarioGroupResponses = {
    200: unknown;
};

export type ScenarioControllerCreateScenarioData = {
    body?: never;
    path: {
        scenarioGroupId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/scenario-group/{scenarioGroupId}/scenario';
};

export type ScenarioControllerCreateScenarioResponses = {
    default: ScenarioDto;
};

export type ScenarioControllerCreateScenarioResponse = ScenarioControllerCreateScenarioResponses[keyof ScenarioControllerCreateScenarioResponses];

export type ScenarioControllerDeleteScenarioData = {
    body?: never;
    path: {
        scenarioId: string;
        scenarioGroupId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/scenario-group/{scenarioGroupId}/scenario/{scenarioId}';
};

export type ScenarioControllerDeleteScenarioResponses = {
    200: unknown;
};

export type ScenarioControllerUpdateScenarioData = {
    body: UpdateScenarioRequestBodyDto;
    path: {
        scenarioId: string;
        scenarioGroupId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/scenario-group/{scenarioGroupId}/scenario/{scenarioId}';
};

export type ScenarioControllerUpdateScenarioResponses = {
    default: ScenarioDto;
};

export type ScenarioControllerUpdateScenarioResponse = ScenarioControllerUpdateScenarioResponses[keyof ScenarioControllerUpdateScenarioResponses];

export type RoomControllerDeleteRoomData = {
    body?: never;
    path: {
        roomId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/room/{roomId}';
};

export type RoomControllerDeleteRoomResponses = {
    200: unknown;
};

export type RoomControllerGetRoomData = {
    body?: never;
    path: {
        roomId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/room/{roomId}';
};

export type RoomControllerGetRoomResponses = {
    default: RoomDto;
};

export type RoomControllerGetRoomResponse = RoomControllerGetRoomResponses[keyof RoomControllerGetRoomResponses];

export type RoomControllerUpdateRoomData = {
    body: UpdateRoomRequestBodyDto;
    path: {
        roomId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/room/{roomId}';
};

export type RoomControllerUpdateRoomResponses = {
    default: RoomDto;
};

export type RoomControllerUpdateRoomResponse = RoomControllerUpdateRoomResponses[keyof RoomControllerUpdateRoomResponses];

export type RoomControllerCreateRoomData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/room';
};

export type RoomControllerCreateRoomResponses = {
    default: RoomDto;
};

export type RoomControllerCreateRoomResponse = RoomControllerCreateRoomResponses[keyof RoomControllerCreateRoomResponses];

export type DatabaseConnectionControllerCreateDatabaseConnectionData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/database-connection';
};

export type DatabaseConnectionControllerCreateDatabaseConnectionResponses = {
    default: DatabaseConnectionDto;
};

export type DatabaseConnectionControllerCreateDatabaseConnectionResponse = DatabaseConnectionControllerCreateDatabaseConnectionResponses[keyof DatabaseConnectionControllerCreateDatabaseConnectionResponses];

export type DatabaseConnectionControllerTestDatabaseConnectionData = {
    body: TestDatabaseConnectionRequestBodyDto;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/database-connection/test';
};

export type DatabaseConnectionControllerTestDatabaseConnectionResponses = {
    default: TestDatabaseConnectionResponseBodyDto;
};

export type DatabaseConnectionControllerTestDatabaseConnectionResponse = DatabaseConnectionControllerTestDatabaseConnectionResponses[keyof DatabaseConnectionControllerTestDatabaseConnectionResponses];

export type DatabaseConnectionControllerDeleteDatabaseConnectionData = {
    body?: never;
    path: {
        databaseConnectionId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/database-connection/{databaseConnectionId}';
};

export type DatabaseConnectionControllerDeleteDatabaseConnectionResponses = {
    200: unknown;
};

export type DatabaseConnectionControllerGetDatabaseConnectionData = {
    body?: never;
    path: {
        databaseConnectionId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/database-connection/{databaseConnectionId}';
};

export type DatabaseConnectionControllerGetDatabaseConnectionResponses = {
    default: DatabaseConnectionDto;
};

export type DatabaseConnectionControllerGetDatabaseConnectionResponse = DatabaseConnectionControllerGetDatabaseConnectionResponses[keyof DatabaseConnectionControllerGetDatabaseConnectionResponses];

export type DatabaseConnectionControllerUpdateDatabaseConnectionData = {
    body: UpdateDatabaseConnectionRequestBodyDto;
    path: {
        databaseConnectionId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/database-connection/{databaseConnectionId}';
};

export type DatabaseConnectionControllerUpdateDatabaseConnectionResponses = {
    default: DatabaseConnectionDto;
};

export type DatabaseConnectionControllerUpdateDatabaseConnectionResponse = DatabaseConnectionControllerUpdateDatabaseConnectionResponses[keyof DatabaseConnectionControllerUpdateDatabaseConnectionResponses];

export type CommonPropertiesControllerCreateCommonPropertyData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/common-property';
};

export type CommonPropertiesControllerCreateCommonPropertyResponses = {
    default: CommonPropertyDto;
};

export type CommonPropertiesControllerCreateCommonPropertyResponse = CommonPropertiesControllerCreateCommonPropertyResponses[keyof CommonPropertiesControllerCreateCommonPropertyResponses];

export type CommonPropertiesControllerDeleteCommonPropertyData = {
    body?: never;
    path: {
        commonPropertyId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/common-property/{commonPropertyId}';
};

export type CommonPropertiesControllerDeleteCommonPropertyResponses = {
    200: unknown;
};

export type CommonPropertiesControllerUpdateCommonPropertyData = {
    body: UpdateCommonPropertyRequestBodyDto;
    path: {
        commonPropertyId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/project/{projectId}/common-property/{commonPropertyId}';
};

export type CommonPropertiesControllerUpdateCommonPropertyResponses = {
    200: unknown;
};

export type PublicRoomControllerGetRoomData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}';
};

export type PublicRoomControllerGetRoomResponses = {
    default: RoomDto;
};

export type PublicRoomControllerGetRoomResponse = PublicRoomControllerGetRoomResponses[keyof PublicRoomControllerGetRoomResponses];

export type PublicCanvasControllerGetCanvasData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}';
};

export type PublicCanvasControllerGetCanvasResponses = {
    default: CanvasPageDto;
};

export type PublicCanvasControllerGetCanvasResponse = PublicCanvasControllerGetCanvasResponses[keyof PublicCanvasControllerGetCanvasResponses];

export type CanvasNoteControllerPostNoteData = {
    body: PostNoteRequestBody;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/note';
};

export type CanvasNoteControllerPostNoteResponses = {
    201: unknown;
};

export type CanvasNoteControllerDeleteNoteData = {
    body?: never;
    path: {
        noteId: string;
        roomId: string;
        canvasId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/note/{noteId}';
};

export type CanvasNoteControllerDeleteNoteResponses = {
    200: unknown;
};

export type CanvasNoteControllerUpdateNoteData = {
    body: UpdateNoteRequestBodyDto;
    path: {
        noteId: string;
        roomId: string;
        canvasId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/note/{noteId}';
};

export type CanvasNoteControllerUpdateNoteResponses = {
    200: unknown;
};

export type CanvasDatabaseConnectionControllerGetStatsData = {
    body?: never;
    path: {
        databaseId: string;
        roomId: string;
        canvasId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/database-connection/{databaseId}/stats';
};

export type CanvasDatabaseConnectionControllerGetStatsResponses = {
    default: GetDatabaseStatsResponseBodyDto;
};

export type CanvasDatabaseConnectionControllerGetStatsResponse = CanvasDatabaseConnectionControllerGetStatsResponses[keyof CanvasDatabaseConnectionControllerGetStatsResponses];

export type CanvasDatabaseConnectionControllerPerformSearchData = {
    body: PostSearchRequestBodyDto;
    path: {
        databaseId: string;
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/database-connection/{databaseId}/search';
};

export type CanvasDatabaseConnectionControllerPerformSearchResponses = {
    default: PostSearchResponseBodyDto;
};

export type CanvasDatabaseConnectionControllerPerformSearchResponse = CanvasDatabaseConnectionControllerPerformSearchResponses[keyof CanvasDatabaseConnectionControllerPerformSearchResponses];

export type CanvasDatabaseConnectionControllerGetSearchCapabilitiesData = {
    body?: never;
    path: {
        databaseId: string;
        roomId: string;
        canvasId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/database-connection/{databaseId}/search-capabilities';
};

export type CanvasDatabaseConnectionControllerGetSearchCapabilitiesResponses = {
    default: GetSearchCapabilitiesResponseBodyDto;
};

export type CanvasDatabaseConnectionControllerGetSearchCapabilitiesResponse = CanvasDatabaseConnectionControllerGetSearchCapabilitiesResponses[keyof CanvasDatabaseConnectionControllerGetSearchCapabilitiesResponses];

export type CanvasDatabaseConnectionControllerExpandNodePreviewData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
        databaseId: string;
    };
    query: {
        nodeId: string;
    };
    url: '/api/room/{roomId}/canvas/{canvasId}/database-connection/{databaseId}/expand-node-preview';
};

export type CanvasDatabaseConnectionControllerExpandNodePreviewResponses = {
    default: ExpandNodePreviewResponseBodyDto;
};

export type CanvasDatabaseConnectionControllerExpandNodePreviewResponse = CanvasDatabaseConnectionControllerExpandNodePreviewResponses[keyof CanvasDatabaseConnectionControllerExpandNodePreviewResponses];

export type ActionControllerLoadScenarioData = {
    body: LoadScenarioRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/load-scenario';
};

export type ActionControllerLoadScenarioResponses = {
    200: unknown;
};

export type ActionControllerReloadScenarioData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/reload-scenario';
};

export type ActionControllerReloadScenarioResponses = {
    200: unknown;
};

export type ActionControllerExpandNodeData = {
    body: ExpandNodeRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/expand-node';
};

export type ActionControllerExpandNodeResponses = {
    200: unknown;
};

export type ActionControllerDeleteElementsData = {
    body: DeleteElementsRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/delete-elements';
};

export type ActionControllerDeleteElementsResponses = {
    200: unknown;
};

export type ActionControllerRelayoutData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/relayout';
};

export type ActionControllerRelayoutResponses = {
    200: unknown;
};

export type ActionControllerUnlockNodesData = {
    body: UnlockNodesRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/unlock-nodes';
};

export type ActionControllerUnlockNodesResponses = {
    200: unknown;
};

export type ActionControllerFocusNodesData = {
    body: FocusNodesRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/focus-nodes';
};

export type ActionControllerFocusNodesResponses = {
    200: unknown;
};

export type ActionControllerFocusRelationshipTypeData = {
    body: FocusRelationshipTypeRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/focus-relationship-type';
};

export type ActionControllerFocusRelationshipTypeResponses = {
    200: unknown;
};

export type ActionControllerUndoData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/undo';
};

export type ActionControllerUndoResponses = {
    200: unknown;
};

export type ActionControllerRedoData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/redo';
};

export type ActionControllerRedoResponses = {
    200: unknown;
};

export type ActionControllerRunQueryData = {
    body: RunQueryRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/run-query';
};

export type ActionControllerRunQueryResponses = {
    200: unknown;
};

export type ActionControllerConnectResultNodesData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/connect-result-nodes';
};

export type ActionControllerConnectResultNodesResponses = {
    200: unknown;
};

export type ActionControllerUnlockAllNodesData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/unlock-all-nodes';
};

export type ActionControllerUnlockAllNodesResponses = {
    200: unknown;
};

export type ActionControllerFlipCanvasData = {
    body: FlipCanvasRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/flip-canvas';
};

export type ActionControllerFlipCanvasResponses = {
    200: unknown;
};

export type ActionControllerRemoveDanglingNodesData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/remove-dangling-nodes';
};

export type ActionControllerRemoveDanglingNodesResponses = {
    200: unknown;
};

export type ActionControllerCompressRelationshipsData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/compress-relationships';
};

export type ActionControllerCompressRelationshipsResponses = {
    200: unknown;
};

export type ActionControllerExpandRelationshipClusterData = {
    body: ExpandRelationshipClusterRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/expand-relationship-cluster';
};

export type ActionControllerExpandRelationshipClusterResponses = {
    200: unknown;
};

export type ActionControllerCompressNodesData = {
    body: CompressNodesRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/compress-nodes';
};

export type ActionControllerCompressNodesResponses = {
    200: unknown;
};

export type ActionControllerLayoutData = {
    body: LayoutRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/layout';
};

export type ActionControllerLayoutResponses = {
    200: unknown;
};

export type ActionControllerShowShortestPathData = {
    body: ShowShortestPathRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/show-shortest-path';
};

export type ActionControllerShowShortestPathResponses = {
    200: unknown;
};

export type ActionControllerLoadNodeData = {
    body: LoadNodeRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/load-node';
};

export type ActionControllerLoadNodeResponses = {
    200: unknown;
};

export type ActionControllerSetViewSettingsData = {
    body: LiveCanvasViewSettingsDto;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/set-view-settings';
};

export type ActionControllerSetViewSettingsResponses = {
    200: unknown;
};

export type ActionControllerResetViewSettingsData = {
    body?: never;
    path: {
        canvasId: string;
        roomId: string;
    };
    query?: never;
    url: '/api/room/{roomId}/canvas/{canvasId}/action/reset-view-settings';
};

export type ActionControllerResetViewSettingsResponses = {
    200: unknown;
};

export type SystemControllerGetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/version';
};

export type SystemControllerGetVersionResponses = {
    default: GetVersionResponseBodyDto;
};

export type SystemControllerGetVersionResponse = SystemControllerGetVersionResponses[keyof SystemControllerGetVersionResponses];

export type RedirectControllerGetUrlData = {
    body?: never;
    path?: never;
    query: {
        url: string;
    };
    url: '/api/redirect/url';
};

export type RedirectControllerGetUrlResponses = {
    default: GetUrlResponseBodyDto;
};

export type RedirectControllerGetUrlResponse = RedirectControllerGetUrlResponses[keyof RedirectControllerGetUrlResponses];
