// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { AuthControllerPostAuthData, AuthControllerPostAuthError, AuthControllerPostAuthResponse, AuthControllerGetAuthError, AuthControllerGetAuthResponse, StartPageControllerGetStartPageData, StartPageControllerGetStartPageError, StartPageControllerGetStartPageResponse } from './types.gen';

export const client = createClient(createConfig());

export const authControllerPostAuth = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<AuthControllerPostAuthData, ThrowOnError>) => {
    return (options?.client ?? client).post<AuthControllerPostAuthResponse, AuthControllerPostAuthError, ThrowOnError>({
        ...options,
        url: '/auth'
    });
};

export const authControllerGetAuth = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<AuthControllerGetAuthResponse, AuthControllerGetAuthError, ThrowOnError>({
        ...options,
        url: '/auth'
    });
};

export const startPageControllerGetStartPage = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<StartPageControllerGetStartPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<StartPageControllerGetStartPageResponse, StartPageControllerGetStartPageError, ThrowOnError>({
        ...options,
        url: '/start-page'
    });
};