// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { AuthControllerPostAuthData, AuthControllerPostAuthError, AuthControllerPostAuthResponse, AuthControllerGetAuthError, AuthControllerGetAuthResponse, StartPageControllerGetStartPageData, StartPageControllerGetStartPageError, StartPageControllerGetStartPageResponse, ProjectPageControllerGetProjectPageData, ProjectPageControllerGetProjectPageError, ProjectPageControllerGetProjectPageResponse, CanvasPageControllerGetCanvasPageData, CanvasPageControllerGetCanvasPageError, CanvasPageControllerGetCanvasPageResponse, RoomControllerGetRoomData, RoomControllerGetRoomError, RoomControllerGetRoomResponse, NoteControllerPostNoteData, NoteControllerPostNoteError, NoteControllerPostNoteResponse, NoteControllerDeleteNoteData, NoteControllerDeleteNoteError, NoteControllerDeleteNoteResponse, NoteControllerUpdateNoteData, NoteControllerUpdateNoteError, NoteControllerUpdateNoteResponse, SystemControllerGetVersionError, SystemControllerGetVersionResponse, DatabaseConnectionControllerGetStatsData, DatabaseConnectionControllerGetStatsError, DatabaseConnectionControllerGetStatsResponse, DatabaseConnectionControllerPerformSearchData, DatabaseConnectionControllerPerformSearchError, DatabaseConnectionControllerPerformSearchResponse, DatabaseConnectionControllerGetSearchCapabilitesData, DatabaseConnectionControllerGetSearchCapabilitesError, DatabaseConnectionControllerGetSearchCapabilitesResponse } from './types.gen';

export const client = createClient(createConfig());

export const authControllerPostAuth = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<AuthControllerPostAuthData, ThrowOnError>) => {
    return (options?.client ?? client).post<AuthControllerPostAuthResponse, AuthControllerPostAuthError, ThrowOnError>({
        ...options,
        url: '/auth'
    });
};

export const authControllerGetAuth = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<AuthControllerGetAuthResponse, AuthControllerGetAuthError, ThrowOnError>({
        ...options,
        url: '/auth'
    });
};

export const startPageControllerGetStartPage = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<StartPageControllerGetStartPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<StartPageControllerGetStartPageResponse, StartPageControllerGetStartPageError, ThrowOnError>({
        ...options,
        url: '/start-page'
    });
};

export const projectPageControllerGetProjectPage = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProjectPageControllerGetProjectPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<ProjectPageControllerGetProjectPageResponse, ProjectPageControllerGetProjectPageError, ThrowOnError>({
        ...options,
        url: '/project-page/id'
    });
};

export const canvasPageControllerGetCanvasPage = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CanvasPageControllerGetCanvasPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<CanvasPageControllerGetCanvasPageResponse, CanvasPageControllerGetCanvasPageError, ThrowOnError>({
        ...options,
        url: '/canvas-page/{id}'
    });
};

export const roomControllerGetRoom = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RoomControllerGetRoomData, ThrowOnError>) => {
    return (options?.client ?? client).get<RoomControllerGetRoomResponse, RoomControllerGetRoomError, ThrowOnError>({
        ...options,
        url: '/room/{id}'
    });
};

export const noteControllerPostNote = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<NoteControllerPostNoteData, ThrowOnError>) => {
    return (options?.client ?? client).post<NoteControllerPostNoteResponse, NoteControllerPostNoteError, ThrowOnError>({
        ...options,
        url: '/note'
    });
};

export const noteControllerDeleteNote = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<NoteControllerDeleteNoteData, ThrowOnError>) => {
    return (options?.client ?? client).delete<NoteControllerDeleteNoteResponse, NoteControllerDeleteNoteError, ThrowOnError>({
        ...options,
        url: '/note/{id}'
    });
};

export const noteControllerUpdateNote = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<NoteControllerUpdateNoteData, ThrowOnError>) => {
    return (options?.client ?? client).put<NoteControllerUpdateNoteResponse, NoteControllerUpdateNoteError, ThrowOnError>({
        ...options,
        url: '/note/{id}'
    });
};

export const systemControllerGetVersion = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<SystemControllerGetVersionResponse, SystemControllerGetVersionError, ThrowOnError>({
        ...options,
        url: '/system/version'
    });
};

export const databaseConnectionControllerGetStats = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DatabaseConnectionControllerGetStatsData, ThrowOnError>) => {
    return (options?.client ?? client).get<DatabaseConnectionControllerGetStatsResponse, DatabaseConnectionControllerGetStatsError, ThrowOnError>({
        ...options,
        url: '/database-connection/{id}/stats'
    });
};

export const databaseConnectionControllerPerformSearch = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DatabaseConnectionControllerPerformSearchData, ThrowOnError>) => {
    return (options?.client ?? client).post<DatabaseConnectionControllerPerformSearchResponse, DatabaseConnectionControllerPerformSearchError, ThrowOnError>({
        ...options,
        url: '/database-connection/{id}/search'
    });
};

export const databaseConnectionControllerGetSearchCapabilites = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DatabaseConnectionControllerGetSearchCapabilitesData, ThrowOnError>) => {
    return (options?.client ?? client).get<DatabaseConnectionControllerGetSearchCapabilitesResponse, DatabaseConnectionControllerGetSearchCapabilitesError, ThrowOnError>({
        ...options,
        url: '/database-connection/{id}/search-capabilities'
    });
};