// This file is auto-generated by @hey-api/openapi-ts

export type DatabaseConnectionDto = {
    id: string;
    title: string;
    browserUrl: string;
    connectionUrl: string;
};

export type GetAuthResponseBodyDto = {
    username: string;
};

export type PostAuthRequestBodyDto = {
    username: string;
    password: string;
};

export type PostAuthResponseBodyDto = {
    jwt: string;
    username: string;
};

export type StartPageDto = {
    myProjects: Array<StartPageProjectDto>;
    collaborationProjects: Array<StartPageProjectDto>;
    recentRooms: Array<StartPageRoomDto>;
    publicRooms: Array<StartPageRoomDto>;
};

export type StartPageProjectDto = {
    id: string;
    title: string;
    owner: ((UserPreviewDto) | null);
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
};

export type StartPageRoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    projectTitle: string;
};

export type visibility = 'private' | 'public' | 'unlisted';

export type UserPreviewDto = {
    id: string;
    displayName: string;
};

export type AuthControllerPostAuthData = {
    body: PostAuthRequestBodyDto;
};

export type AuthControllerPostAuthResponse = (PostAuthResponseBodyDto);

export type AuthControllerPostAuthError = unknown;

export type AuthControllerGetAuthResponse = (GetAuthResponseBodyDto);

export type AuthControllerGetAuthError = unknown;

export type StartPageControllerGetStartPageData = {
    query: {
        recentRoomIds: Array<(string)>;
    };
};

export type StartPageControllerGetStartPageResponse = (StartPageDto);

export type StartPageControllerGetStartPageError = unknown;