// This file is auto-generated by @hey-api/openapi-ts

export type CanvasDto = {
    id: string;
    title: string;
};

export type CanvasPageDto = {
    canvas: CanvasDto;
    scenarios: ScenarioCollectionDto;
    room: RoomDto;
};

export type ColorCustomDto = {
    backgroundColor: string;
    textColor: string;
};

export type ColorDto = {
    color: (ColorPresetDto | ColorCustomDto);
};

export type ColorPresetDto = {
    index: 0 | 1 | 2 | 3 | 4 | 5;
};

export type index = 0 | 1 | 2 | 3 | 4 | 5;

export type DatabaseConnectionDto = {
    id: string;
    title: string;
    browserUrl: string;
    connectionUrl: string;
};

export type DatabaseStatsLabelDto = {
    label: string;
    exploreQuery: string;
};

export type DatabaseStatsRelationshipDto = {
    relType: string;
    exploreQuery: string;
};

export type GetAuthResponseBodyDto = {
    username: string;
};

export type GetDatabaseStatsResponseBodyDto = {
    relTypeCount: number;
    labelCount: number;
    relCount: number;
    labels: Array<DatabaseStatsLabelDto>;
    rels: Array<DatabaseStatsRelationshipDto>;
    nodeCount: number;
};

export type GetSearchCapabilitiesResponseBodyDto = {
    canExactMatchElementId: boolean;
    canExactMatchLabel: boolean;
    exactMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
    fuzzyMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
};

export type GetVersionResponseBodyDto = {
    version: string;
};

export type NodePreviewDto = {
    id: string;
    title: string;
    labels: Array<(string)>;
    customColor: ((ColorDto) | null);
};

export type PostAuthRequestBodyDto = {
    username: string;
    password: string;
};

export type PostAuthResponseBodyDto = {
    jwt: string;
    username: string;
};

export type PostNoteRequestBody = {
    nodeIds: Array<(string)>;
    content: string;
};

export type PostSearchRequestBodyDto = {
    searchTerm: string;
};

export type PostSearchResponseBodyDto = {
    nodes: Array<NodePreviewDto>;
};

export type ProjectPageDto = {
    id: string;
    title: string;
    owner: ((UserPreviewDto) | null);
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
    scenarioGroups: Array<ScenarioGroupDto>;
    rooms: Array<RoomDto>;
};

export type RoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    canvases: Array<CanvasDto>;
};

export type visibility = 'private' | 'public' | 'unlisted';

export type ScenarioCollectionDto = {
    scenarioGroups: Array<ScenarioGroupDto>;
    parameterizedScenarios: Array<ScenarioGroupDto>;
    referencedDatabases: Array<DatabaseConnectionDto>;
};

export type ScenarioDto = {
    id: string;
    title: (string) | null;
    queries: Array<ScenarioQueryDto>;
    description: (string) | null;
    parameters: Array<ScenarioParameterDto>;
    postActions: Array<(string)>;
};

export type ScenarioGroupDto = {
    id: string;
    title: string;
    scenarios: Array<ScenarioDto>;
};

export type ScenarioParameterDto = {
    identifier: string;
    title: string;
    defaultValue: {
        [key: string]: unknown;
    } | null;
    dataType: 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';
};

export type dataType = 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';

export type ScenarioQueryDto = {
    query: string;
    database: ((DatabaseConnectionDto) | null);
};

export type SearchCapabilitiesEntryDto = {
    label: string;
    property: string;
};

export type StartPageDto = {
    myProjects: Array<StartPageProjectDto>;
    collaborationProjects: Array<StartPageProjectDto>;
    recentRooms: Array<StartPageRoomDto>;
    publicRooms: Array<StartPageRoomDto>;
};

export type StartPageProjectDto = {
    id: string;
    title: string;
    owner: ((UserPreviewDto) | null);
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
};

export type StartPageRoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    projectTitle: string;
};

export type UpdateNoteRequestBodyDto = {
    content: string;
};

export type UserPreviewDto = {
    id: string;
    displayName: string;
};

export type AuthControllerPostAuthData = {
    body: PostAuthRequestBodyDto;
};

export type AuthControllerPostAuthResponse = (PostAuthResponseBodyDto);

export type AuthControllerPostAuthError = unknown;

export type AuthControllerGetAuthResponse = (GetAuthResponseBodyDto);

export type AuthControllerGetAuthError = unknown;

export type StartPageControllerGetStartPageData = {
    query: {
        recentRoomIds: Array<(string)>;
    };
};

export type StartPageControllerGetStartPageResponse = (StartPageDto);

export type StartPageControllerGetStartPageError = unknown;

export type ProjectPageControllerGetProjectPageData = {
    path: {
        projectId: string;
    };
};

export type ProjectPageControllerGetProjectPageResponse = (ProjectPageDto);

export type ProjectPageControllerGetProjectPageError = unknown;

export type CanvasPageControllerGetCanvasPageData = {
    path: {
        canvasId: string;
    };
};

export type CanvasPageControllerGetCanvasPageResponse = (CanvasPageDto);

export type CanvasPageControllerGetCanvasPageError = unknown;

export type RoomControllerGetRoomData = {
    path: {
        roomId: string;
    };
};

export type RoomControllerGetRoomResponse = (RoomDto);

export type RoomControllerGetRoomError = unknown;

export type NoteControllerPostNoteData = {
    body: PostNoteRequestBody;
    path: {
        roomId: string;
    };
};

export type NoteControllerPostNoteResponse = (unknown);

export type NoteControllerPostNoteError = unknown;

export type NoteControllerDeleteNoteData = {
    path: {
        noteId: string;
        roomId: string;
    };
};

export type NoteControllerDeleteNoteResponse = (unknown);

export type NoteControllerDeleteNoteError = unknown;

export type NoteControllerUpdateNoteData = {
    body: UpdateNoteRequestBodyDto;
    path: {
        noteId: string;
        roomId: string;
    };
};

export type NoteControllerUpdateNoteResponse = (unknown);

export type NoteControllerUpdateNoteError = unknown;

export type SystemControllerGetVersionResponse = (GetVersionResponseBodyDto);

export type SystemControllerGetVersionError = unknown;

export type DatabaseConnectionControllerGetStatsData = {
    path: {
        databaseId: string;
        roomId: string;
    };
};

export type DatabaseConnectionControllerGetStatsResponse = (GetDatabaseStatsResponseBodyDto);

export type DatabaseConnectionControllerGetStatsError = unknown;

export type DatabaseConnectionControllerPerformSearchData = {
    body: PostSearchRequestBodyDto;
    path: {
        databaseId: string;
        roomId: string;
    };
};

export type DatabaseConnectionControllerPerformSearchResponse = (PostSearchResponseBodyDto);

export type DatabaseConnectionControllerPerformSearchError = unknown;

export type DatabaseConnectionControllerGetSearchCapabilitesData = {
    path: {
        databaseId: string;
        roomId: string;
    };
};

export type DatabaseConnectionControllerGetSearchCapabilitesResponse = (GetSearchCapabilitiesResponseBodyDto);

export type DatabaseConnectionControllerGetSearchCapabilitesError = unknown;