// This file is auto-generated by @hey-api/openapi-ts

export type ActionWsdto = {
    action: (JoinCanvasWsdto | LeaveCanvasWsdto | GrabNodeWsdto | MoveNodesWsdto | UngrabNodeWsdto);
};

export type CanvasDto = {
    id: string;
    title: string;
};

export type CanvasPageDto = {
    canvas: CanvasDto;
    scenarios: ScenarioCollectionDto;
    room: RoomDto;
};

export type ColorCustomDto = {
    backgroundColor: string;
    textColor: string;
};

export type ColorDto = {
    color: (ColorPresetDto | ColorCustomDto);
};

export type ColorPresetDto = {
    index: 0 | 1 | 2 | 3 | 4 | 5;
};

export type index = 0 | 1 | 2 | 3 | 4 | 5;

export type CompressNodesRequestBodyDto = {
    label: string;
};

export type DatabaseConnectionDto = {
    id: string;
    title: string;
    browserUrl: string;
    connectionUrl: string;
};

export type DatabaseStatsLabelDto = {
    label: string;
    exploreQuery: string;
};

export type DatabaseStatsRelationshipDto = {
    relType: string;
    exploreQuery: string;
};

export type DeleteElementsRequestBodyDto = {
    nodes: Array<(string)>;
    edges: Array<(string)>;
    labels: Array<(string)>;
    edgeTypes: Array<(string)>;
};

export type ExpandNodeLimitDto = {
    labels: Array<(string)>;
    relationships: Array<(string)>;
};

export type ExpandNodePreviewEntryDto = {
    identificator: string;
    count: number;
};

export type ExpandNodePreviewResponseBodyDto = {
    relationships: Array<ExpandNodePreviewEntryDto>;
    labels: Array<ExpandNodePreviewEntryDto>;
};

export type ExpandNodeRequestBodyDto = {
    nodeIds: Array<(string)>;
    limit: ((ExpandNodeLimitDto) | null);
};

export type FocusNodesRequestBodyDto = {
    nodes: Array<(string)>;
};

export type GetAuthResponseBodyDto = {
    username: string;
};

export type GetDatabaseStatsResponseBodyDto = {
    relTypeCount: number;
    labelCount: number;
    relCount: number;
    labels: Array<DatabaseStatsLabelDto>;
    rels: Array<DatabaseStatsRelationshipDto>;
    nodeCount: number;
};

export type GetSearchCapabilitiesResponseBodyDto = {
    canExactMatchElementId: boolean;
    canExactMatchLabel: boolean;
    exactMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
    fuzzyMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
};

export type GetVersionResponseBodyDto = {
    version: string;
};

export type GrabNodeWsdto = {
    type: 'GrabNodeWsdto';
    nodeId: string;
};

export type type = 'GrabNodeWsdto';

export type JoinCanvasWsdto = {
    type: 'JoinCanvasWsdto';
    canvasId: string;
};

export type type2 = 'JoinCanvasWsdto';

export type LayoutLabelRequestBodyDto = {
    label: string;
    layoutSpecification: (LayoutSpecificationCircleDto | LayoutSpecificationForceDirectedDto);
};

export type LayoutSpecificationCircleDto = {
    type: 'LayoutSpecificationCircleDto';
    radius: number;
};

export type type3 = 'LayoutSpecificationCircleDto';

export type LayoutSpecificationForceDirectedDto = {
    type: 'LayoutSpecificationForceDirectedDto';
};

export type type4 = 'LayoutSpecificationForceDirectedDto';

export type LeaveCanvasWsdto = {
    type: 'LeaveCanvasWsdto';
};

export type type5 = 'LeaveCanvasWsdto';

export type LiveCanvasViewSettingsDto = {
    compressRelationshipsWidthFactor: number;
    growNodesBasedOnDegree: boolean;
    growNodesBasedOnDegreeFactor: number;
};

export type LoadNodeRequestBodyDto = {
    nodeId: string;
    databaseId: string;
};

export type LoadScenarioRequestBodyDto = {
    scenarioId: string;
    additive: boolean;
    arguments: Array<ScenarioArgumentDto>;
};

export type MoveNodesWsdto = {
    type: 'MoveNodesWsdto';
    nodes: Array<PhysicalNodeWsdto>;
};

export type type6 = 'MoveNodesWsdto';

export type NodePreviewDto = {
    id: string;
    title: string;
    labels: Array<(string)>;
    customColor: ((ColorDto) | null);
};

export type PhysicalNodeWsdto = {
    id: string;
    positionX: number;
    positionY: number;
};

export type PostAuthRequestBodyDto = {
    username: string;
    password: string;
};

export type PostAuthResponseBodyDto = {
    jwt: string;
    username: string;
};

export type PostNoteRequestBody = {
    nodeIds: Array<(string)>;
    content: string;
};

export type PostSearchRequestBodyDto = {
    searchTerm: string;
};

export type PostSearchResponseBodyDto = {
    nodes: Array<NodePreviewDto>;
};

export type ProjectPageDto = {
    id: string;
    title: string;
    owner: ((UserPreviewDto) | null);
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
    scenarioGroups: Array<ScenarioGroupDto>;
    rooms: Array<RoomDto>;
};

export type RoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    canvases: Array<CanvasDto>;
};

export type visibility = 'private' | 'public' | 'unlisted';

export type RunQueryRequestBodyDto = {
    databaseId: string;
    query: string;
    replace: boolean;
};

export type ScenarioArgumentDto = {
    identifier: string;
    value: string;
};

export type ScenarioCollectionDto = {
    scenarioGroups: Array<ScenarioGroupDto>;
    parameterizedScenarios: Array<ScenarioGroupDto>;
    referencedDatabases: Array<DatabaseConnectionDto>;
};

export type ScenarioDto = {
    id: string;
    title: (string) | null;
    queries: Array<ScenarioQueryDto>;
    description: (string) | null;
    parameters: Array<ScenarioParameterDto>;
    postActions: Array<(string)>;
};

export type ScenarioGroupDto = {
    id: string;
    title: string;
    scenarios: Array<ScenarioDto>;
};

export type ScenarioParameterDto = {
    identifier: string;
    title: string;
    defaultValue: (string) | null;
    dataType: 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';
};

export type dataType = 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';

export type ScenarioQueryDto = {
    query: string;
    database: ((DatabaseConnectionDto) | null);
};

export type SearchCapabilitiesEntryDto = {
    label: string;
    property: string;
};

export type ShowShortestPathRequestBodyDto = {
    nodeIds: Array<(string)>;
};

export type StartPageDto = {
    myProjects: Array<StartPageProjectDto>;
    collaborationProjects: Array<StartPageProjectDto>;
    recentRooms: Array<StartPageRoomDto>;
    publicRooms: Array<StartPageRoomDto>;
};

export type StartPageProjectDto = {
    id: string;
    title: string;
    owner: ((UserPreviewDto) | null);
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
};

export type StartPageRoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    projectTitle: string;
};

export type UngrabNodeWsdto = {
    type: 'UngrabNodeWsdto';
    node: PhysicalNodeWsdto;
};

export type type7 = 'UngrabNodeWsdto';

export type UnlockNodesRequestBodyDto = {
    nodes: Array<(string)>;
};

export type UpdateNoteRequestBodyDto = {
    content: string;
};

export type UserPreviewDto = {
    id: string;
    displayName: string;
};

export type AuthControllerPostAuthData = {
    body: PostAuthRequestBodyDto;
};

export type AuthControllerPostAuthResponse = (PostAuthResponseBodyDto);

export type AuthControllerPostAuthError = unknown;

export type AuthControllerGetAuthResponse = (GetAuthResponseBodyDto);

export type AuthControllerGetAuthError = unknown;

export type StartPageControllerGetStartPageData = {
    query: {
        recentRoomIds: Array<(string)>;
    };
};

export type StartPageControllerGetStartPageResponse = (StartPageDto);

export type StartPageControllerGetStartPageError = unknown;

export type ProjectPageControllerGetProjectPageData = {
    path: {
        projectId: string;
    };
};

export type ProjectPageControllerGetProjectPageResponse = (ProjectPageDto);

export type ProjectPageControllerGetProjectPageError = unknown;

export type CanvasPageControllerGetCanvasPageData = {
    path: {
        canvasId: string;
    };
};

export type CanvasPageControllerGetCanvasPageResponse = (CanvasPageDto);

export type CanvasPageControllerGetCanvasPageError = unknown;

export type RoomControllerGetRoomData = {
    path: {
        roomId: string;
    };
};

export type RoomControllerGetRoomResponse = (RoomDto);

export type RoomControllerGetRoomError = unknown;

export type NoteControllerPostNoteData = {
    body: PostNoteRequestBody;
    path: {
        roomId: string;
    };
};

export type NoteControllerPostNoteResponse = (unknown);

export type NoteControllerPostNoteError = unknown;

export type NoteControllerDeleteNoteData = {
    path: {
        noteId: string;
        roomId: string;
    };
};

export type NoteControllerDeleteNoteResponse = (unknown);

export type NoteControllerDeleteNoteError = unknown;

export type NoteControllerUpdateNoteData = {
    body: UpdateNoteRequestBodyDto;
    path: {
        noteId: string;
        roomId: string;
    };
};

export type NoteControllerUpdateNoteResponse = (unknown);

export type NoteControllerUpdateNoteError = unknown;

export type SystemControllerGetVersionResponse = (GetVersionResponseBodyDto);

export type SystemControllerGetVersionError = unknown;

export type DatabaseConnectionControllerGetStatsData = {
    path: {
        databaseId: string;
        roomId: string;
    };
};

export type DatabaseConnectionControllerGetStatsResponse = (GetDatabaseStatsResponseBodyDto);

export type DatabaseConnectionControllerGetStatsError = unknown;

export type DatabaseConnectionControllerPerformSearchData = {
    body: PostSearchRequestBodyDto;
    path: {
        databaseId: string;
        roomId: string;
    };
};

export type DatabaseConnectionControllerPerformSearchResponse = (PostSearchResponseBodyDto);

export type DatabaseConnectionControllerPerformSearchError = unknown;

export type DatabaseConnectionControllerGetSearchCapabilitesData = {
    path: {
        databaseId: string;
        roomId: string;
    };
};

export type DatabaseConnectionControllerGetSearchCapabilitesResponse = (GetSearchCapabilitiesResponseBodyDto);

export type DatabaseConnectionControllerGetSearchCapabilitesError = unknown;

export type DatabaseConnectionControllerExpandNodePreviewData = {
    path: {
        databaseId: string;
        roomId: string;
    };
    query: {
        nodeId: string;
    };
};

export type DatabaseConnectionControllerExpandNodePreviewResponse = (ExpandNodePreviewResponseBodyDto);

export type DatabaseConnectionControllerExpandNodePreviewError = unknown;

export type ActionControllerLoadScenarioData = {
    body: LoadScenarioRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerLoadScenarioResponse = (unknown);

export type ActionControllerLoadScenarioError = unknown;

export type ActionControllerReloadScenarioData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerReloadScenarioResponse = (unknown);

export type ActionControllerReloadScenarioError = unknown;

export type ActionControllerExpandNodeData = {
    body: ExpandNodeRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerExpandNodeResponse = (unknown);

export type ActionControllerExpandNodeError = unknown;

export type ActionControllerDeleteElementsData = {
    body: DeleteElementsRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerDeleteElementsResponse = (unknown);

export type ActionControllerDeleteElementsError = unknown;

export type ActionControllerRelayoutData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerRelayoutResponse = (unknown);

export type ActionControllerRelayoutError = unknown;

export type ActionControllerUnlockNodesData = {
    body: UnlockNodesRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerUnlockNodesResponse = (unknown);

export type ActionControllerUnlockNodesError = unknown;

export type ActionControllerFocusNodesData = {
    body: FocusNodesRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerFocusNodesResponse = (unknown);

export type ActionControllerFocusNodesError = unknown;

export type ActionControllerUndoData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerUndoResponse = (unknown);

export type ActionControllerUndoError = unknown;

export type ActionControllerRedoData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerRedoResponse = (unknown);

export type ActionControllerRedoError = unknown;

export type ActionControllerRunQueryData = {
    body: RunQueryRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerRunQueryResponse = (unknown);

export type ActionControllerRunQueryError = unknown;

export type ActionControllerConnectResultNodesData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerConnectResultNodesResponse = (unknown);

export type ActionControllerConnectResultNodesError = unknown;

export type ActionControllerUnlockAllNodesData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerUnlockAllNodesResponse = (unknown);

export type ActionControllerUnlockAllNodesError = unknown;

export type ActionControllerRemoveDanglingNodesData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerRemoveDanglingNodesResponse = (unknown);

export type ActionControllerRemoveDanglingNodesError = unknown;

export type ActionControllerCompressRelationshipsData = {
    path: {
        canvasId: string;
    };
};

export type ActionControllerCompressRelationshipsResponse = (unknown);

export type ActionControllerCompressRelationshipsError = unknown;

export type ActionControllerCompressNodesData = {
    body: CompressNodesRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerCompressNodesResponse = (unknown);

export type ActionControllerCompressNodesError = unknown;

export type ActionControllerLayoutLabelData = {
    body: LayoutLabelRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerLayoutLabelResponse = (unknown);

export type ActionControllerLayoutLabelError = unknown;

export type ActionControllerShowShortestPathData = {
    body: ShowShortestPathRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerShowShortestPathResponse = (unknown);

export type ActionControllerShowShortestPathError = unknown;

export type ActionControllerLoadNodeData = {
    body: LoadNodeRequestBodyDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerLoadNodeResponse = (unknown);

export type ActionControllerLoadNodeError = unknown;

export type ActionControllerSetViewSettingsData = {
    body: LiveCanvasViewSettingsDto;
    path: {
        canvasId: string;
    };
};

export type ActionControllerSetViewSettingsResponse = (unknown);

export type ActionControllerSetViewSettingsError = unknown;