// This file is auto-generated by @hey-api/openapi-ts

export type Color = PresetColor | CustomColor;

export type CustomColor = {
    backgroundColor: string;
    textColor: string;
};

export type Database = {
    id: string;
    title: (string) | null;
    url: (string) | null;
    browserUrl: (string) | null;
    editUrl: (string) | null;
    scenarioGroups: Array<ScenarioGroup>;
};

export type Databases = {
    databases: Array<Database>;
};

export type Edge = {
    id: string;
    startNodeId: string;
    endNodeId: string;
    type: string;
    isLoop: boolean;
    parallelCount: number;
    parallelIndex: number;
    compressedCount: number;
    width: number;
    properties: Array<GraphProperty>;
    namesInQuery: Array<(string)>;
    source: string;
};

export type Graph = {
    nodes: Array<Node>;
    edges: Array<Edge>;
    metaData: GraphMetaData;
    tableData: Array<{
        [key: string]: unknown;
    }>;
};

export type GraphLabel = {
    label: string;
    color: Color;
    count: number;
    sources: Array<(string)>;
};

export type GraphMetaData = {
    labels: Array<GraphLabel>;
    scenarioInfo: ScenarioInfo;
    pipelineSummary: Array<{
        step: string;
        durationMs: number;
    }>;
    histogram: Histogram;
};

export type GraphProperty = {
    slug: string;
    value: GraphPropertyValue;
};

export type GraphPropertyValue = unknown;

export type Histogram = {
    nodeLabels: Array<{
        label: string;
        count: number;
        percentage: number;
    }>;
    nodeProperties: Array<{
        key: string;
        values: Array<{
            value: string;
            count: number;
            percentage: number;
        }>;
    }>;
    edgeTypes: Array<{
        type: string;
        count: number;
        percentage: number;
    }>;
    edgeProperties: Array<{
        key: string;
        values: Array<{
            value: string;
            count: number;
            percentage: number;
        }>;
    }>;
};

export type Node = {
    id: string;
    title: string;
    labels: Array<(string)>;
    properties: Array<GraphProperty>;
    radius: number;
    position: Position;
    inDegree: number;
    outDegree: number;
    degree: number;
    namesInQuery: Array<(string)>;
    displayConfigurationContext: unknown;
    customBackgroundColor: (string) | null;
    customTitleColor: (string) | null;
    source: string;
    additionalSources: Array<(string)>;
    locked: boolean;
};

export type PhysicalNode = {
    id: string;
    position: Position;
};

export type PhysicsPerformance = {
    performance: 'good' | 'bad';
    loadPercent: number;
    tickDuration: number;
};

export type performance = 'good' | 'bad';

export type Position = {
    x: number;
    y: number;
};

export type PresetColor = {
    index: PresetColorIndex;
};

export type PresetColorIndex = 0 | 1 | 2 | 3 | 4 | 5;

export type Room = {
    id: string;
    title: (string) | null;
    scenario: {
        current: Scenario;
    } | null;
    editUrl: (string) | null;
};

export type Rooms = {
    rooms: Array<Room>;
};

export type Scenario = {
    id: string;
    title: (string) | null;
    query: (string) | null;
    description: (string) | null;
    coverUrl: (string) | null;
    editUrl: (string) | null;
};

export type ScenarioGroup = {
    id: string;
    title: (string) | null;
    editUrl: (string) | null;
    scenarios: Array<Scenario>;
};

export type ScenarioInfo = {
    id: string;
    title: (string) | null;
} | null;

export type Version = {
    version: string;
};

export type WSActionDeleteNodes = {
    type: 'WSActionDeleteNodes';
    nodes: Array<(string)>;
};

export type type = 'WSActionDeleteNodes';

export type WSActionExpandNodes = {
    type: 'WSActionExpandNodes';
    nodes: Array<(string)>;
};

export type type2 = 'WSActionExpandNodes';

export type WSActionGetGraph = {
    type: 'WSActionGetGraph';
};

export type type3 = 'WSActionGetGraph';

export type WSActionGrabNode = {
    type: 'WSActionGrabNode';
    nodeId: string;
};

export type type4 = 'WSActionGrabNode';

export type WSActionJoinRoom = {
    type: 'WSActionJoinRoom';
    roomId: string;
};

export type type5 = 'WSActionJoinRoom';

export type WSActionLoadScenario = {
    type: 'WSActionLoadScenario';
    scenarioId: string;
};

export type type6 = 'WSActionLoadScenario';

export type WSActionMoveNodes = {
    type: 'WSActionMoveNodes';
    nodes: Array<PhysicalNode>;
};

export type type7 = 'WSActionMoveNodes';

export type WSActionRelayout = {
    type: 'WSActionRelayout';
};

export type type8 = 'WSActionRelayout';

export type WSActionUngrabNode = {
    type: 'WSActionUngrabNode';
    node: PhysicalNode;
};

export type type9 = 'WSActionUngrabNode';

export type WSActionUnlockNodes = {
    type: 'WSActionUnlockNodes';
    nodes: Array<(string)>;
};

export type type10 = 'WSActionUnlockNodes';

export type WSClientToServerMessage = WSActionJoinRoom | WSActionLoadScenario | WSActionGetGraph | WSActionGrabNode | WSActionMoveNodes | WSActionUngrabNode | WSActionExpandNodes | WSActionDeleteNodes | WSActionRelayout | WSActionUnlockNodes;

export type WSEventClearProgress = {
    type: 'WSEventClearProgress';
};

export type type11 = 'WSEventClearProgress';

export type WSEventGraphChanged = {
    type: 'WSEventGraphChanged';
    graph: Graph;
};

export type type12 = 'WSEventGraphChanged';

export type WSEventLockUi = {
    type: 'WSEventLockUi';
};

export type type13 = 'WSEventLockUi';

export type WSEventNodesMoved = {
    type: 'WSEventNodesMoved';
    nodes: Array<PhysicalNode>;
    date: string;
};

export type type14 = 'WSEventNodesMoved';

export type WSEventNotification = {
    type: 'WSEventNotification';
    title: string;
    message: string;
    severity: 'error' | 'message' | 'warning';
    date: string;
};

export type type15 = 'WSEventNotification';

export type severity = 'error' | 'message' | 'warning';

export type WSEventPerformanceChanged = {
    type: 'WSEventPerformanceChanged';
    performance?: PhysicsPerformance;
};

export type type16 = 'WSEventPerformanceChanged';

export type WSEventProgress = {
    type: 'WSEventProgress';
    progress: (number) | null;
    message: string;
};

export type type17 = 'WSEventProgress';

export type WSEventRoomChanged = {
    type: 'WSEventRoomChanged';
    roomId: (string) | null;
};

export type type18 = 'WSEventRoomChanged';

export type WSEventSetLocks = {
    type: 'WSEventSetLocks';
    locks: Array<{
        id: string;
        locked: boolean;
    }>;
};

export type type19 = 'WSEventSetLocks';

export type WSEventUnlockUi = {
    type: 'WSEventUnlockUi';
};

export type type20 = 'WSEventUnlockUi';

export type WSServerToClientMessage = WSEventNodesMoved | WSEventRoomChanged | WSEventNotification | WSEventGraphChanged | WSEventProgress | WSEventClearProgress | WSEventSetLocks | WSEventLockUi | WSEventUnlockUi | WSEventPerformanceChanged;

export type GetScenariosResponse = (Databases);

export type GetScenariosError = unknown;

export type GetRoomsResponse = (Rooms);

export type GetRoomsError = unknown;

export type GetRoomData = {
    path: {
        id: string;
    };
};

export type GetRoomResponse = (Room);

export type GetRoomError = unknown;

export type GetVersionResponse = (Version);

export type GetVersionError = unknown;