// This file is auto-generated by @hey-api/openapi-ts

export type Color = PresetColor | CustomColor;

export type CreationReason = 'loadScenario' | 'expand' | 'query' | 'merge' | 'compress' | 'connectResultNodes' | 'search';

export type CustomColor = {
    type: 'CustomColor';
    backgroundColor: string;
    textColor: string;
};

export type type = 'CustomColor';

export type Database = {
    id: string;
    title: (string) | null;
    url: (string) | null;
    browserUrl: (string) | null;
    editUrl: (string) | null;
};

export type DatabaseSearchCapabilities = {
    canExactMatchElementId: boolean;
    canExactMatchLabel: boolean;
    exactMatchNodeProperties: Array<DatabaseSearchCapabilitiesEntry>;
    fuzzyMatchNodeProperties: Array<DatabaseSearchCapabilitiesEntry>;
};

export type DatabaseSearchCapabilitiesEntry = {
    label: string;
    property: string;
};

export type DatabaseStats = {
    relTypeCount: number;
    labelCount: number;
    relCount: number;
    labels: Array<{
        label: string;
        exploreQuery: string;
    }>;
    rels: Array<{
        relType: string;
        exploreQuery: string;
    }>;
    nodeCount: number;
};

export type Edge = {
    id: string;
    startNodeId: string;
    endNodeId: string;
    type: string;
    isLoop: boolean;
    parallelCount: number;
    parallelIndex: number;
    isCluster: boolean;
    width: number;
    properties: Array<GraphProperty>;
    namesInQuery: Array<(string)>;
    source: string;
    clusterSize: number;
    sourceNode: NodePreview;
    targetNode: NodePreview;
    creationReason: CreationReason;
};

export type EdgePreview = {
    type: string;
    count: number;
    percentage: number;
};

export type ExpandNodePreviewElement = {
    identificator: string;
    count: number;
};

export type GetScenariosResult = {
    scenarioGroups: Array<ScenarioGroup>;
    parameterizedScenarios: Array<ScenarioGroup>;
    referencedDatabases: Array<Database>;
};

export type Graph = {
    elements: GraphElements;
    metaData: GraphMetaData;
    table: GraphTable;
};

export type GraphElements = {
    nodes: Array<Node>;
    edges: Array<Edge>;
    labels: Array<GraphLabel>;
    histogram: Histogram;
    notes: Array<Note>;
};

export type GraphLabel = {
    label: string;
    color: Color;
    count: number;
    sources: Array<(string)>;
};

export type GraphMetaData = {
    scenario?: {
        current: Scenario;
    } | null;
    pipelineSummary: Array<{
        step: string;
        durationMs: number;
    }>;
    arguments: Array<ScenarioArgument>;
    canUndo: boolean;
    canRedo: boolean;
};

export type GraphProperty = {
    slug: string;
    value: GraphPropertyValue;
};

export type GraphPropertyValue = unknown;

export type GraphTable = {
    data: Array<{
        [key: string]: unknown;
    }>;
};

export type Histogram = {
    nodeLabels: Array<{
        label: string;
        count: number;
        percentage: number;
    }>;
    nodeProperties: Array<{
        key: string;
        values: Array<{
            value: string;
            count: number;
            percentage: number;
        }>;
    }>;
    edgeTypes: Array<{
        type: string;
        count: number;
        percentage: number;
    }>;
    edgeProperties: Array<{
        key: string;
        values: Array<{
            value: string;
            count: number;
            percentage: number;
        }>;
    }>;
    nodes: Array<{
        id: string;
        title: string;
        labels: Array<(string)>;
        degree: number;
        percentage: number;
        customColor: {
            color: Color;
        } | null;
    }>;
};

export type LayoutSpecification = LayoutSpecificationForceDirected | LayoutSpecificationCircle;

export type LayoutSpecificationCircle = {
    type: 'LayoutSpecificationCircle';
    radius: number;
};

export type type2 = 'LayoutSpecificationCircle';

export type LayoutSpecificationForceDirected = {
    type: 'LayoutSpecificationForceDirected';
};

export type type3 = 'LayoutSpecificationForceDirected';

export type Node = {
    id: string;
    title: string;
    labels: Array<(string)>;
    nativeLabels: Array<(string)>;
    properties: Array<GraphProperty>;
    radius: number;
    position: Position;
    inDegree: number;
    outDegree: number;
    degree: number;
    namesInQuery: Array<(string)>;
    customColor: {
        color: Color;
    } | null;
    customTitleColor?: (string) | null;
    source: string;
    locked: boolean;
    isCluster: boolean;
    clusterSize: number;
    incomingEdges: Array<EdgePreview>;
    outgoingEdges: Array<EdgePreview>;
    creationReason: CreationReason;
    notes: Array<Note>;
};

export type NodePreview = {
    id: string;
    title: string;
    labels: Array<(string)>;
    customColor: {
        color: Color;
    } | null;
};

export type Note = {
    id: string;
    content: string;
    nodes: Array<NodePreview>;
    author: (string) | null;
    dateTime: string;
    color: {
        color: Color;
    } | null;
};

export type Notification = {
    message: string;
    severity: 'error' | 'message' | 'warning';
    date: string;
};

export type severity = 'error' | 'message' | 'warning';

export type PhysicalNode = {
    id: string;
    position: Position;
};

export type PhysicsPerformance = {
    performance: 'good' | 'bad';
    loadPercent: number;
    tickDuration: number;
    tickCount: number;
};

export type performance = 'good' | 'bad';

export type Position = {
    x: number;
    y: number;
};

export type PresetColor = {
    type: 'PresetColor';
    index: PresetColorIndex;
};

export type type4 = 'PresetColor';

export type PresetColorIndex = 0 | 1 | 2 | 3 | 4 | 5;

export type Room = {
    id: string;
    title: (string) | null;
    scenario: {
        current: Scenario;
    } | null;
    editUrl: (string) | null;
    template: {
        id: string;
        title: (string) | null;
        editUrl: (string) | null;
    } | null;
};

export type Rooms = {
    rooms: Array<Room>;
};

export type RoomTemplate = {
    id: string;
    title: (string) | null;
    editUrl: (string) | null;
};

export type RoomTemplates = {
    roomTemplates: Array<RoomTemplate>;
};

export type Scenario = {
    id: string;
    title: (string) | null;
    queries: Array<ScenarioQuery>;
    description: (string) | null;
    coverUrl: (string) | null;
    editUrl: (string) | null;
    parameters: Array<ScenarioParameter>;
    additive: boolean;
};

export type ScenarioArgument = {
    identifier: string;
    value: string;
};

export type ScenarioGroup = {
    id: string;
    title: (string) | null;
    editUrl: (string) | null;
    scenarios: Array<Scenario>;
};

export type ScenarioParameter = {
    identifier: string;
    title: string;
    defaultValue: (string) | null;
    dataType: 'json' | 'startDateTime' | 'endDateTime';
};

export type dataType = 'json' | 'startDateTime' | 'endDateTime';

export type ScenarioQuery = {
    query: string;
    database: {
        current: Database;
    } | null;
};

export type Version = {
    version: string;
};

export type WSActionGrabNode = {
    type: 'WSActionGrabNode';
    nodeId: string;
};

export type type5 = 'WSActionGrabNode';

export type WSActionJoinRoom = {
    type: 'WSActionJoinRoom';
    roomId: string;
};

export type type6 = 'WSActionJoinRoom';

export type WSActionLeaveRoom = {
    type: 'WSActionLeaveRoom';
};

export type type7 = 'WSActionLeaveRoom';

export type WSActionMoveNodes = {
    type: 'WSActionMoveNodes';
    nodes: Array<PhysicalNode>;
};

export type type8 = 'WSActionMoveNodes';

export type WSActionUngrabNode = {
    type: 'WSActionUngrabNode';
    node: PhysicalNode;
};

export type type9 = 'WSActionUngrabNode';

export type WSClientToServerMessage = WSActionJoinRoom | WSActionLeaveRoom | WSActionGrabNode | WSActionMoveNodes | WSActionUngrabNode;

export type WSEventClearProgress = {
    type: 'WSEventClearProgress';
};

export type type10 = 'WSEventClearProgress';

export type WSEventGraphElementsChanged = {
    type: 'WSEventGraphElementsChanged';
    elements: GraphElements;
};

export type type11 = 'WSEventGraphElementsChanged';

export type WSEventGraphMetaDataChanged = {
    type: 'WSEventGraphMetaDataChanged';
    metaData: GraphMetaData;
};

export type type12 = 'WSEventGraphMetaDataChanged';

export type WSEventGraphTableChanged = {
    type: 'WSEventGraphTableChanged';
    table: GraphTable;
};

export type type13 = 'WSEventGraphTableChanged';

export type WSEventKick = {
    type: 'WSEventKick';
};

export type type14 = 'WSEventKick';

export type WSEventLockUi = {
    type: 'WSEventLockUi';
};

export type type15 = 'WSEventLockUi';

export type WSEventNodesMoved = {
    type: 'WSEventNodesMoved';
    nodes: Array<PhysicalNode>;
    date: string;
    performance: PhysicsPerformance;
};

export type type16 = 'WSEventNodesMoved';

export type WSEventNotification = {
    type: 'WSEventNotification';
    notification: Notification;
};

export type type17 = 'WSEventNotification';

export type WSEventProgress = {
    type: 'WSEventProgress';
    progress: (number) | null;
    message: string;
};

export type type18 = 'WSEventProgress';

export type WSEventRoomChanged = {
    type: 'WSEventRoomChanged';
    roomId: (string) | null;
};

export type type19 = 'WSEventRoomChanged';

export type WSEventSetNodeLocks = {
    type: 'WSEventSetNodeLocks';
    locks: Array<{
        id: string;
        locked: boolean;
    }>;
};

export type type20 = 'WSEventSetNodeLocks';

export type WSEventUnlockUi = {
    type: 'WSEventUnlockUi';
};

export type type21 = 'WSEventUnlockUi';

export type WSServerToClientMessage = WSEventNodesMoved | WSEventRoomChanged | WSEventNotification | WSEventGraphElementsChanged | WSEventGraphMetaDataChanged | WSEventGraphTableChanged | WSEventProgress | WSEventClearProgress | WSEventSetNodeLocks | WSEventLockUi | WSEventUnlockUi | WSEventKick;

export type PostAuthData = {
    body: {
        username: string;
        password: string;
    };
};

export type PostAuthResponse = ({
    jwt: string;
    username: string;
});

export type PostAuthError = unknown;

export type GetAuthResponse = ({
    username: string;
});

export type GetAuthError = unknown;

export type GetScenariosData = {
    path: {
        id: string;
    };
};

export type GetScenariosResponse = (GetScenariosResult);

export type GetScenariosError = unknown;

export type GetRoomsResponse = (Rooms);

export type GetRoomsError = unknown;

export type CreateRoomData = {
    body: {
        templateId: string;
    };
};

export type CreateRoomResponse = (Room);

export type CreateRoomError = unknown;

export type GetRoomData = {
    path: {
        id: string;
    };
};

export type GetRoomResponse = (Room);

export type GetRoomError = unknown;

export type GetRoomTemplatesResponse = (RoomTemplates);

export type GetRoomTemplatesError = unknown;

export type GetRoomTemplateData = {
    path: {
        id: string;
    };
};

export type GetRoomTemplateResponse = (RoomTemplate);

export type GetRoomTemplateError = unknown;

export type GetRoomGraphData = {
    path: {
        id: string;
    };
};

export type GetRoomGraphResponse = (Graph);

export type GetRoomGraphError = unknown;

export type GetRoomGraphElementsData = {
    path: {
        id: string;
    };
};

export type GetRoomGraphElementsResponse = (GraphElements);

export type GetRoomGraphElementsError = unknown;

export type GetRoomGraphMetaDataData = {
    path: {
        id: string;
    };
};

export type GetRoomGraphMetaDataResponse = (GraphMetaData);

export type GetRoomGraphMetaDataError = unknown;

export type GetRoomGraphTableData = {
    path: {
        id: string;
    };
};

export type GetRoomGraphTableResponse = (GraphTable);

export type GetRoomGraphTableError = unknown;

export type PostNoteData = {
    body: {
        nodeIds: Array<(string)>;
        content: string;
        color: {
            color: Color;
        } | null;
    };
    path: {
        id: string;
    };
};

export type PostNoteResponse = (unknown);

export type PostNoteError = unknown;

export type DeleteNoteData = {
    path: {
        id: string;
        noteId: string;
    };
};

export type DeleteNoteResponse = (unknown);

export type DeleteNoteError = unknown;

export type PutNoteData = {
    body: {
        nodeIds: Array<(string)>;
        content: string;
        color: {
            color: Color;
        } | null;
    };
    path: {
        id: string;
        noteId: string;
    };
};

export type PutNoteResponse = (unknown);

export type PutNoteError = unknown;

export type PostRoomActionLoadScenarioData = {
    body: {
        scenarioId: string;
        arguments: Array<ScenarioArgument>;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionLoadScenarioResponse = (unknown);

export type PostRoomActionLoadScenarioError = unknown;

export type PostRoomActionReloadScenarioData = {
    path: {
        id: string;
    };
};

export type PostRoomActionReloadScenarioResponse = (unknown);

export type PostRoomActionReloadScenarioError = unknown;

export type PostRoomActionExpandNodeData = {
    body: {
        nodeId: string;
        limit: {
            labels: Array<(string)>;
            relationships: Array<(string)>;
        } | null;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionExpandNodeResponse = (unknown);

export type PostRoomActionExpandNodeError = unknown;

export type PostRoomActionExpandNodePreviewData = {
    body: {
        nodeId: string;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionExpandNodePreviewResponse = ({
    relationships: Array<ExpandNodePreviewElement>;
    labels: Array<ExpandNodePreviewElement>;
} | null);

export type PostRoomActionExpandNodePreviewError = unknown;

export type PostRoomActionDeleteElementsData = {
    body: {
        nodes: Array<(string)>;
        edges: Array<(string)>;
        labels: Array<(string)>;
        edgeTypes: Array<(string)>;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionDeleteElementsResponse = (unknown);

export type PostRoomActionDeleteElementsError = unknown;

export type PostRoomActionRelayoutData = {
    path: {
        id: string;
    };
};

export type PostRoomActionRelayoutResponse = (unknown);

export type PostRoomActionRelayoutError = unknown;

export type PostRoomActionUnlockNodesData = {
    body: {
        nodes: Array<(string)>;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionUnlockNodesResponse = (unknown);

export type PostRoomActionUnlockNodesError = unknown;

export type PostRoomActionFocusNodesData = {
    body: {
        nodes: Array<(string)>;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionFocusNodesResponse = (unknown);

export type PostRoomActionFocusNodesError = unknown;

export type PostRoomActionUndoData = {
    path: {
        id: string;
    };
};

export type PostRoomActionUndoResponse = (unknown);

export type PostRoomActionUndoError = unknown;

export type PostRoomActionRedoData = {
    path: {
        id: string;
    };
};

export type PostRoomActionRedoResponse = (unknown);

export type PostRoomActionRedoError = unknown;

export type PostRoomActionRunQueryData = {
    body: {
        databaseId: string;
        query: string;
        replace: boolean;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionRunQueryResponse = (unknown);

export type PostRoomActionRunQueryError = unknown;

export type PostRoomActionConnectResultNodesData = {
    path: {
        id: string;
    };
};

export type PostRoomActionConnectResultNodesResponse = (unknown);

export type PostRoomActionConnectResultNodesError = unknown;

export type PostRoomActionUnlockAllNodesData = {
    path: {
        id: string;
    };
};

export type PostRoomActionUnlockAllNodesResponse = (unknown);

export type PostRoomActionUnlockAllNodesError = unknown;

export type PostRoomActionRemoveDanglingNodesData = {
    path: {
        id: string;
    };
};

export type PostRoomActionRemoveDanglingNodesResponse = (unknown);

export type PostRoomActionRemoveDanglingNodesError = unknown;

export type PostRoomActionCompressRelationshipsData = {
    path: {
        id: string;
    };
};

export type PostRoomActionCompressRelationshipsResponse = (unknown);

export type PostRoomActionCompressRelationshipsError = unknown;

export type PostRoomActionCompressNodesData = {
    body: {
        label: string;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionCompressNodesResponse = (unknown);

export type PostRoomActionCompressNodesError = unknown;

export type PostRoomActionLayoutLabelData = {
    body: {
        label: string;
        layoutSpecification: LayoutSpecification;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionLayoutLabelResponse = (unknown);

export type PostRoomActionLayoutLabelError = unknown;

export type PostRoomActionShowShortestPathData = {
    body: {
        nodeIds: Array<(string)>;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionShowShortestPathResponse = (unknown);

export type PostRoomActionShowShortestPathError = unknown;

export type PostRoomActionLoadNodeData = {
    body: {
        nodeId: string;
        databaseId: string;
    };
    path: {
        id: string;
    };
};

export type PostRoomActionLoadNodeResponse = (unknown);

export type PostRoomActionLoadNodeError = unknown;

export type GetDatabaseStatsData = {
    path: {
        id: string;
    };
};

export type GetDatabaseStatsResponse = (DatabaseStats);

export type GetDatabaseStatsError = unknown;

export type PostDatabaseSearchData = {
    body: {
        searchTerm: string;
        roomId: string;
    };
    path: {
        id: string;
    };
};

export type PostDatabaseSearchResponse = ({
    nodes: Array<Node>;
});

export type PostDatabaseSearchError = unknown;

export type GetDatabaseSearchCapabilitiesData = {
    path: {
        id: string;
    };
};

export type GetDatabaseSearchCapabilitiesResponse = (DatabaseSearchCapabilities);

export type GetDatabaseSearchCapabilitiesError = unknown;

export type GetVersionResponse = (Version);

export type GetVersionError = unknown;

export type GetBackupResponse = (unknown);

export type GetBackupError = unknown;

export type PostImportData = {
    body: {
        /**
         * The file to upload.
         */
        file?: (Blob | File);
    };
};

export type PostImportResponse = (unknown);

export type PostImportError = unknown;