// This file is auto-generated by @hey-api/openapi-ts

export type ActionWsdto = {
    action: (GrabNodeWsdto | MoveNodesWsdto | UngrabNodeWsdto | MoveCursorWsdto);
};

export type AuthWsdto = {
    jwt: string;
    canvasId: string;
};

export type CanvasChangedWsdto = {
    type: 'CanvasChangedWsdto';
    canvasId: Array<(string)>;
};

export type type = 'CanvasChangedWsdto';

export type CanvasDataReadyWsdto = {
    type: 'CanvasDataReadyWsdto';
    data: LiveCanvasDataDto;
};

export type type2 = 'CanvasDataReadyWsdto';

export type CanvasDto = {
    id: string;
    title: string;
};

export type CanvasElementsChangedWsdto = {
    type: 'CanvasElementsChangedWsdto';
    elements: LiveCanvasGraphElementsDto;
};

export type type3 = 'CanvasElementsChangedWsdto';

export type CanvasHistogramChangedWsdto = {
    type: 'CanvasHistogramChangedWsdto';
    histogram: HistogramDto;
};

export type type4 = 'CanvasHistogramChangedWsdto';

export type CanvasMetaDataChangedWsdto = {
    type: 'CanvasMetaDataChangedWsdto';
    metaData: LiveCanvasMetaDataDto;
};

export type type5 = 'CanvasMetaDataChangedWsdto';

export type CanvasNotesChangedWsdto = {
    type: 'CanvasNotesChangedWsdto';
    notes: Array<NoteDto>;
};

export type type6 = 'CanvasNotesChangedWsdto';

export type CanvasPageDto = {
    canvas: CanvasDto;
    scenarios: ScenarioCollectionDto;
    room: RoomDto;
};

export type CanvasTableDataChangedWsdto = {
    type: 'CanvasTableDataChangedWsdto';
    table: LiveCanvasTableDataDto;
};

export type type7 = 'CanvasTableDataChangedWsdto';

export type CanvasViewSettingsChangedWsdto = {
    type: 'CanvasViewSettingsChangedWsdto';
    viewSettings: LiveCanvasViewSettingsDto;
};

export type type8 = 'CanvasViewSettingsChangedWsdto';

export type ClearProgressWsdto = {
    type: 'ClearProgressWsdto';
};

export type type9 = 'ClearProgressWsdto';

export type ColorCustomDto = {
    type: 'ColorCustomDto';
    backgroundColor: string;
    textColor: string;
};

export type type10 = 'ColorCustomDto';

export type ColorDto = {
    color: (ColorPresetDto | ColorCustomDto);
};

export type ColorPresetDto = {
    type: 'ColorPresetDto';
    index: 0 | 1 | 2 | 3 | 4 | 5;
};

export type type11 = 'ColorPresetDto';

export type index = 0 | 1 | 2 | 3 | 4 | 5;

export type CommonPropertyDto = {
    id: string;
    leftLabel: string;
    leftProperty: string;
    rightLabel: string;
    rightProperty: string;
    leftDatabase: ((DatabaseConnectionDto) | null);
    rightDatabase: ((DatabaseConnectionDto) | null);
};

export type CompressNodesRequestBodyDto = {
    label: string;
};

export type CreateProjectRequestBodyDto = {
    title: string;
};

export type CursorMovedWsdto = {
    type: 'CursorMovedWsdto';
    position: PositionDto;
    socketId: string;
};

export type type12 = 'CursorMovedWsdto';

export type DatabaseConnectionDto = {
    id: string;
    title: string;
    browserUrl: string;
    connectionUrl: string;
    database: string;
};

export type DatabaseStatsLabelDto = {
    label: string;
    exploreQuery: string;
};

export type DatabaseStatsRelationshipDto = {
    relType: string;
    exploreQuery: string;
};

export type DeleteElementsRequestBodyDto = {
    nodes: Array<(string)>;
    edges: Array<(string)>;
    labels: Array<(string)>;
    edgeTypes: Array<(string)>;
};

export type EdgeDto = {
    id: string;
    startNodeId: string;
    endNodeId: string;
    type: string;
    isLoop: boolean;
    parallelCount: number;
    parallelIndex: number;
    isCluster: boolean;
    width: number;
    properties: {
        [key: string]: unknown;
    };
    namesInQuery: Array<(string)>;
    source: string;
    clusterSize: number;
    sourceNode: NodePreviewDto;
    targetNode: NodePreviewDto;
    creationReason: 'loadScenario' | 'expand' | 'query' | 'merge' | 'compress' | 'connectResultNodes' | 'search';
};

export type creationReason = 'loadScenario' | 'expand' | 'query' | 'merge' | 'compress' | 'connectResultNodes' | 'search';

export type EdgePreviewDto = {
    type: string;
    count: number;
    percentage: number;
};

export type EventWsdto = {
    event: (CanvasChangedWsdto | CanvasDataReadyWsdto | ClearProgressWsdto | CanvasElementsChangedWsdto | CanvasMetaDataChangedWsdto | CanvasTableDataChangedWsdto | CanvasHistogramChangedWsdto | CanvasNotesChangedWsdto | KickWsdto | NodesMovedWsdto | NotificationWsdto | ProgressWsdto | SetNodeLocksWsdto | CanvasViewSettingsChangedWsdto | CursorMovedWsdto);
};

export type ExpandNodeLimitDto = {
    labels: Array<(string)>;
    relationships: Array<(string)>;
};

export type ExpandNodePreviewEntryDto = {
    identificator: string;
    count: number;
};

export type ExpandNodePreviewResponseBodyDto = {
    relationships: Array<ExpandNodePreviewEntryDto>;
    labels: Array<ExpandNodePreviewEntryDto>;
};

export type ExpandNodeRequestBodyDto = {
    nodeIds: Array<(string)>;
    limit: ((ExpandNodeLimitDto) | null);
};

export type FocusNodesRequestBodyDto = {
    nodes: Array<(string)>;
};

export type GetAuthResponseBodyDto = {
    username: string;
};

export type GetDatabaseStatsResponseBodyDto = {
    relTypeCount: number;
    labelCount: number;
    relCount: number;
    labels: Array<DatabaseStatsLabelDto>;
    rels: Array<DatabaseStatsRelationshipDto>;
    nodeCount: number;
};

export type GetSearchCapabilitiesResponseBodyDto = {
    canExactMatchElementId: boolean;
    canExactMatchLabel: boolean;
    exactMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
    fuzzyMatchNodeProperties: Array<SearchCapabilitiesEntryDto>;
};

export type GetUrlResponseBodyDto = {
    url: string;
};

export type GetVersionResponseBodyDto = {
    version: string;
};

export type GrabNodeWsdto = {
    type: 'GrabNodeWsdto';
    nodeId: string;
};

export type type13 = 'GrabNodeWsdto';

export type HistogramDto = {
    nodeLabels: Array<HistogramValueEntryDto>;
    nodeProperties: Array<HistogramPropertyEntryDto>;
    edgeTypes: Array<HistogramValueEntryDto>;
    edgeProperties: Array<HistogramPropertyEntryDto>;
    nodes: Array<HistogramNodeEntryDto>;
};

export type HistogramNodeEntryDto = {
    id: string;
    title: string;
    labels: Array<(string)>;
    degree: number;
    percentage: number;
    customColor: ((ColorDto) | null);
};

export type HistogramPropertyEntryDto = {
    key: string;
    values: Array<HistogramValueEntryDto>;
};

export type HistogramValueEntryDto = {
    value: string;
    count: number;
    percentage: number;
};

export type KickWsdto = {
    type: 'KickWsdto';
};

export type type14 = 'KickWsdto';

export type LabelDto = {
    label: string;
    color: ColorDto;
    count: number;
    sources: Array<(string)>;
};

export type LayoutLabelRequestBodyDto = {
    label: string;
    layoutSpecification: (LayoutSpecificationCircleDto | LayoutSpecificationForceDirectedDto);
};

export type LayoutSpecificationCircleDto = {
    type: 'LayoutSpecificationCircleDto';
    radius: number;
};

export type type15 = 'LayoutSpecificationCircleDto';

export type LayoutSpecificationForceDirectedDto = {
    type: 'LayoutSpecificationForceDirectedDto';
};

export type type16 = 'LayoutSpecificationForceDirectedDto';

export type LiveCanvasDataDto = {
    metaData: LiveCanvasMetaDataDto;
    elements: LiveCanvasGraphElementsDto;
    table: LiveCanvasTableDataDto;
    viewSettings: LiveCanvasViewSettingsDto;
    histogram: HistogramDto;
    notes: Array<NoteDto>;
};

export type LiveCanvasGraphElementsDto = {
    nodes: Array<NodeDto>;
    edges: Array<EdgeDto>;
    labels: Array<LabelDto>;
};

export type LiveCanvasLabelViewSettingsDto = {
    label: string;
    radius: number;
    customRadius: boolean;
    colorIndex: 0 | 1 | 2 | 3 | 4 | 5;
    customColorIndex: boolean;
};

export type colorIndex = 0 | 1 | 2 | 3 | 4 | 5;

export type LiveCanvasMetaDataDto = {
    scenario: ((ScenarioDto) | null);
    arguments: Array<ScenarioArgumentDto>;
    undoAction: (string) | null;
    redoAction: (string) | null;
    users: Array<UserPreviewDto>;
};

export type LiveCanvasTableDataDto = {
    data: Array<{
        [key: string]: unknown;
    }>;
};

export type LiveCanvasViewSettingsDto = {
    compressRelationshipsWidthFactor: number;
    growNodesBasedOnDegree: boolean;
    growNodesBasedOnDegreeFactor: number;
    labelSettings: Array<LiveCanvasLabelViewSettingsDto>;
};

export type LoadNodeRequestBodyDto = {
    nodeId: string;
    databaseId: string;
};

export type LoadScenarioRequestBodyDto = {
    scenarioId: string;
    additive: boolean;
    arguments: Array<ScenarioArgumentDto>;
};

export type MoveCursorWsdto = {
    type: 'MoveCursorWsdto';
    position: PositionDto;
};

export type type17 = 'MoveCursorWsdto';

export type MoveNodesWsdto = {
    type: 'MoveNodesWsdto';
    nodes: Array<PhysicalNodeDto>;
};

export type type18 = 'MoveNodesWsdto';

export type NodeDto = {
    id: string;
    title: string;
    labels: Array<(string)>;
    nativeLabels: Array<(string)>;
    properties: {
        [key: string]: unknown;
    };
    radius: number;
    position: PositionDto;
    inDegree: number;
    outDegree: number;
    degree: number;
    namesInQuery: Array<(string)>;
    customColor: ((ColorDto) | null);
    source: string;
    sourceId: string;
    locked: boolean;
    isCluster: boolean;
    clusterSize: number;
    incomingEdges: Array<EdgePreviewDto>;
    outgoingEdges: Array<EdgePreviewDto>;
    creationReason: 'loadScenario' | 'expand' | 'query' | 'merge' | 'compress' | 'connectResultNodes' | 'search';
    notes: Array<NoteDto>;
    parameterizedScenarios: Array<ScenarioGroupDto>;
};

export type NodeLockCollectionEntryDto = {
    id: string;
    locked: boolean;
};

export type NodePreviewDto = {
    id: string;
    title: string;
    labels: Array<(string)>;
    customColor: ((ColorDto) | null);
};

export type NodesMovedWsdto = {
    type: 'NodesMovedWsdto';
    nodes: Array<PhysicalNodeDto>;
    date: string;
    performance: PhysicsPerformanceDto;
};

export type type19 = 'NodesMovedWsdto';

export type NoteDto = {
    id: string;
    content: string;
    nodes: Array<NodePreviewDto>;
    author: ((UserPreviewDto) | null);
    dateTime: string;
    color: ((ColorDto) | null);
};

export type NotificationDataDto = {
    message: string;
    severity: 'error' | 'message' | 'warning';
    date: string;
};

export type severity = 'error' | 'message' | 'warning';

export type NotificationWsdto = {
    type: 'NotificationWsdto';
    notification: NotificationDataDto;
};

export type type20 = 'NotificationWsdto';

export type PhysicalNodeDto = {
    id: string;
    position: PositionDto;
};

export type PhysicsPerformanceDto = {
    performance: 'good' | 'bad';
    loadPercent: number;
    tickDuration: number;
    tickCount: number;
};

export type performance = 'good' | 'bad';

export type PositionDto = {
    x: number;
    y: number;
};

export type PostAuthRequestBodyDto = {
    username: string;
    password: string;
};

export type PostAuthResponseBodyDto = {
    jwt: string;
    username: string;
};

export type PostNoteRequestBody = {
    nodeIds: Array<(string)>;
    content: string;
};

export type PostSearchRequestBodyDto = {
    searchTerm: string;
};

export type PostSearchResponseBodyDto = {
    nodes: Array<NodePreviewDto>;
};

export type ProgressWsdto = {
    type: 'ProgressWsdto';
    progress: (number) | null;
    message: string;
};

export type type21 = 'ProgressWsdto';

export type ProjectPageDto = {
    id: string;
    title: string;
    owner: ((UserPreviewDto) | null);
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
    scenarioGroups: Array<ScenarioGroupDto>;
    rooms: Array<RoomDto>;
    commonProperties: Array<CommonPropertyDto>;
};

export type RoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    canvases: Array<CanvasDto>;
    joinCanvasId: string;
    projectId: string;
    databases: Array<DatabaseConnectionDto>;
};

export type visibility = 'private' | 'public' | 'unlisted';

export type RunQueryRequestBodyDto = {
    databaseId: string;
    query: string;
    replace: boolean;
};

export type ScenarioArgumentDto = {
    identifier: string;
    value: string;
};

export type ScenarioCollectionDto = {
    scenarioGroups: Array<ScenarioGroupDto>;
};

export type ScenarioDto = {
    id: string;
    title: (string) | null;
    queries: Array<ScenarioQueryDto>;
    description: (string) | null;
    parameters: Array<ScenarioParameterDto>;
    postScenarioActions: Array<ScenarioPostActionDto>;
    postActionsDescription: Array<(string)>;
};

export type ScenarioGroupDto = {
    id: string;
    title: string;
    scenarios: Array<ScenarioDto>;
};

export type ScenarioParameterDto = {
    id: string;
    identifier: string;
    title: string;
    defaultValue: (string) | null;
    dataType: 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';
    allowedLabels: Array<(string)>;
};

export type dataType = 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';

export type ScenarioPostActionDto = {
    id: string;
    type: 'connectResultNodes' | 'compressRelationships' | 'compressNodes' | 'layout' | 'none';
    label: string;
    circleRadius: number;
    layoutAlgorithm: 'forceDirected' | 'circle' | 'none';
};

export type type22 = 'connectResultNodes' | 'compressRelationships' | 'compressNodes' | 'layout' | 'none';

export type layoutAlgorithm = 'forceDirected' | 'circle' | 'none';

export type ScenarioQueryDto = {
    id: string;
    query: string;
    database: ((DatabaseConnectionDto) | null);
    isTableQuery: boolean;
};

export type SearchCapabilitiesEntryDto = {
    label: string;
    property: string;
};

export type SetNodeLocksWsdto = {
    type: 'SetNodeLocksWsdto';
    locks: Array<NodeLockCollectionEntryDto>;
};

export type type23 = 'SetNodeLocksWsdto';

export type ShowShortestPathRequestBodyDto = {
    nodeIds: Array<(string)>;
};

export type StartPageDto = {
    myProjects: Array<StartPageProjectDto>;
    collaborationProjects: Array<StartPageProjectDto>;
    recentRooms: Array<StartPageRoomDto>;
    publicRooms: Array<StartPageRoomDto>;
};

export type StartPageProjectDto = {
    id: string;
    title: string;
    owner: ((UserPreviewDto) | null);
    collaborators: Array<UserPreviewDto>;
    databases: Array<DatabaseConnectionDto>;
};

export type StartPageRoomDto = {
    id: string;
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
    joinCanvasId: string;
};

export type TestDatabaseConnectionRequestBodyDto = {
    id: (string) | null;
    username: (string) | null;
    password: (string) | null;
    database: (string) | null;
    connectionUrl: string;
};

export type TestDatabaseConnectionResponseBodyDto = {
    success: boolean;
    message: string;
};

export type UngrabNodeWsdto = {
    type: 'UngrabNodeWsdto';
    node: PhysicalNodeDto;
};

export type type24 = 'UngrabNodeWsdto';

export type UnlockNodesRequestBodyDto = {
    nodes: Array<(string)>;
};

export type UpdateCommonPropertyRequestBodyDto = {
    leftLabel: string;
    leftProperty: string;
    rightLabel: string;
    rightProperty: string;
    leftDatabaseId: string;
    rightDatabaseId: string;
};

export type UpdateDatabaseConnectionRequestBodyDto = {
    title: string;
    username: (string) | null;
    password: (string) | null;
    database: string;
    connectionUrl: string;
    browserUrl: string;
    credentialStoreConsent: boolean;
};

export type UpdateNoteRequestBodyDto = {
    content: string;
};

export type UpdateProjectRequestBodyDto = {
    title: string;
};

export type UpdateRoomRequestBodyDto = {
    title: string;
    visibility: 'private' | 'public' | 'unlisted';
};

export type UpdateScenarioGroupRequestBodyDto = {
    title: string;
};

export type UpdateScenarioPostActionEntryDto = {
    id: string;
    type: 'connectResultNodes' | 'compressRelationships' | 'compressNodes' | 'layout';
    label: string;
    circleRadius: number;
    layoutAlgorithm: 'forceDirected' | 'circle';
};

export type type25 = 'connectResultNodes' | 'compressRelationships' | 'compressNodes' | 'layout';

export type layoutAlgorithm2 = 'forceDirected' | 'circle';

export type UpdateScenarioQueryEntryDto = {
    id: string;
    query: string;
    databaseId: (string) | null;
    isTableQuery: boolean;
};

export type UpdateScenarioQueryParameterEntryDto = {
    id: string;
    identifier: string;
    title: string;
    defaultValue: string;
    dataType: 'string' | 'number' | 'json' | 'startDateTime' | 'endDateTime';
    allowedLabels: Array<(string)>;
};

export type UpdateScenarioRequestBodyDto = {
    title: string;
    description: string;
    queries: Array<UpdateScenarioQueryEntryDto>;
    parameters: Array<UpdateScenarioQueryParameterEntryDto>;
    postScenarioActions: Array<UpdateScenarioPostActionEntryDto>;
};

export type UserPreviewDto = {
    id: string;
    displayName: (string) | null;
};

export type AuthControllerPostAuthData = {
    body: PostAuthRequestBodyDto;
};

export type AuthControllerPostAuthResponse = (PostAuthResponseBodyDto);

export type AuthControllerPostAuthError = unknown;

export type AuthControllerGetAuthResponse = (GetAuthResponseBodyDto);

export type AuthControllerGetAuthError = unknown;

export type StartControllerGetStartData = {
    query: {
        recentRoomIds: (string) | null;
    };
};

export type StartControllerGetStartResponse = (StartPageDto);

export type StartControllerGetStartError = unknown;

export type ProjectControllerGetProjectData = {
    path: {
        projectId: string;
    };
};

export type ProjectControllerGetProjectResponse = (ProjectPageDto);

export type ProjectControllerGetProjectError = unknown;

export type ProjectControllerUpdateProjectData = {
    body: UpdateProjectRequestBodyDto;
    path: {
        projectId: string;
    };
};

export type ProjectControllerUpdateProjectResponse = (ProjectPageDto);

export type ProjectControllerUpdateProjectError = unknown;

export type ProjectControllerDeleteProjectData = {
    path: {
        projectId: string;
    };
};

export type ProjectControllerDeleteProjectResponse = (unknown);

export type ProjectControllerDeleteProjectError = unknown;

export type ProjectControllerCreateProjectData = {
    body: CreateProjectRequestBodyDto;
};

export type ProjectControllerCreateProjectResponse = (ProjectPageDto);

export type ProjectControllerCreateProjectError = unknown;

export type ScenarioGroupControllerCreateScenarioGroupData = {
    path: {
        projectId: string;
    };
};

export type ScenarioGroupControllerCreateScenarioGroupResponse = (ScenarioGroupDto);

export type ScenarioGroupControllerCreateScenarioGroupError = unknown;

export type ScenarioGroupControllerDeleteScenarioGroupData = {
    path: {
        projectId: string;
        scenarioGroupId: string;
    };
};

export type ScenarioGroupControllerDeleteScenarioGroupResponse = (unknown);

export type ScenarioGroupControllerDeleteScenarioGroupError = unknown;

export type ScenarioGroupControllerUpdateScenarioGroupData = {
    body: UpdateScenarioGroupRequestBodyDto;
    path: {
        projectId: string;
        scenarioGroupId: string;
    };
};

export type ScenarioGroupControllerUpdateScenarioGroupResponse = (unknown);

export type ScenarioGroupControllerUpdateScenarioGroupError = unknown;

export type ScenarioControllerCreateScenarioData = {
    path: {
        projectId: string;
        scenarioGroupId: string;
    };
};

export type ScenarioControllerCreateScenarioResponse = (ScenarioDto);

export type ScenarioControllerCreateScenarioError = unknown;

export type ScenarioControllerDeleteScenarioData = {
    path: {
        projectId: string;
        scenarioGroupId: string;
        scenarioId: string;
    };
};

export type ScenarioControllerDeleteScenarioResponse = (unknown);

export type ScenarioControllerDeleteScenarioError = unknown;

export type ScenarioControllerUpdateScenarioData = {
    body: UpdateScenarioRequestBodyDto;
    path: {
        projectId: string;
        scenarioGroupId: string;
        scenarioId: string;
    };
};

export type ScenarioControllerUpdateScenarioResponse = (ScenarioDto);

export type ScenarioControllerUpdateScenarioError = unknown;

export type RoomControllerGetRoomData = {
    path: {
        projectId: string;
        roomId: string;
    };
};

export type RoomControllerGetRoomResponse = (RoomDto);

export type RoomControllerGetRoomError = unknown;

export type RoomControllerUpdateRoomData = {
    body: UpdateRoomRequestBodyDto;
    path: {
        projectId: string;
        roomId: string;
    };
};

export type RoomControllerUpdateRoomResponse = (RoomDto);

export type RoomControllerUpdateRoomError = unknown;

export type RoomControllerDeleteRoomData = {
    path: {
        projectId: string;
        roomId: string;
    };
};

export type RoomControllerDeleteRoomResponse = (unknown);

export type RoomControllerDeleteRoomError = unknown;

export type RoomControllerCreateRoomData = {
    path: {
        projectId: string;
    };
};

export type RoomControllerCreateRoomResponse = (RoomDto);

export type RoomControllerCreateRoomError = unknown;

export type DatabaseConnectionControllerCreateDatabaseConnectionData = {
    path: {
        projectId: string;
    };
};

export type DatabaseConnectionControllerCreateDatabaseConnectionResponse = (DatabaseConnectionDto);

export type DatabaseConnectionControllerCreateDatabaseConnectionError = unknown;

export type DatabaseConnectionControllerTestDatabaseConnectionData = {
    body: TestDatabaseConnectionRequestBodyDto;
    path: {
        projectId: string;
    };
};

export type DatabaseConnectionControllerTestDatabaseConnectionResponse = (TestDatabaseConnectionResponseBodyDto);

export type DatabaseConnectionControllerTestDatabaseConnectionError = unknown;

export type DatabaseConnectionControllerDeleteDatabaseConnectionData = {
    path: {
        databaseConnectionId: string;
        projectId: string;
    };
};

export type DatabaseConnectionControllerDeleteDatabaseConnectionResponse = (unknown);

export type DatabaseConnectionControllerDeleteDatabaseConnectionError = unknown;

export type DatabaseConnectionControllerGetDatabaseConnectionData = {
    path: {
        databaseConnectionId: string;
        projectId: string;
    };
};

export type DatabaseConnectionControllerGetDatabaseConnectionResponse = (DatabaseConnectionDto);

export type DatabaseConnectionControllerGetDatabaseConnectionError = unknown;

export type DatabaseConnectionControllerUpdateDatabaseConnectionData = {
    body: UpdateDatabaseConnectionRequestBodyDto;
    path: {
        databaseConnectionId: string;
        projectId: string;
    };
};

export type DatabaseConnectionControllerUpdateDatabaseConnectionResponse = (DatabaseConnectionDto);

export type DatabaseConnectionControllerUpdateDatabaseConnectionError = unknown;

export type CommonPropertiesControllerCreateCommonPropertyData = {
    path: {
        projectId: string;
    };
};

export type CommonPropertiesControllerCreateCommonPropertyResponse = (CommonPropertyDto);

export type CommonPropertiesControllerCreateCommonPropertyError = unknown;

export type CommonPropertiesControllerDeleteCommonPropertyData = {
    path: {
        commonPropertyId: string;
        projectId: string;
    };
};

export type CommonPropertiesControllerDeleteCommonPropertyResponse = (unknown);

export type CommonPropertiesControllerDeleteCommonPropertyError = unknown;

export type CommonPropertiesControllerUpdateCommonPropertyData = {
    body: UpdateCommonPropertyRequestBodyDto;
    path: {
        commonPropertyId: string;
        projectId: string;
    };
};

export type CommonPropertiesControllerUpdateCommonPropertyResponse = (unknown);

export type CommonPropertiesControllerUpdateCommonPropertyError = unknown;

export type PublicRoomControllerGetRoomData = {
    path: {
        roomId: string;
    };
};

export type PublicRoomControllerGetRoomResponse = (RoomDto);

export type PublicRoomControllerGetRoomError = unknown;

export type PublicCanvasControllerGetCanvasData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type PublicCanvasControllerGetCanvasResponse = (CanvasPageDto);

export type PublicCanvasControllerGetCanvasError = unknown;

export type CanvasNoteControllerPostNoteData = {
    body: PostNoteRequestBody;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type CanvasNoteControllerPostNoteResponse = (unknown);

export type CanvasNoteControllerPostNoteError = unknown;

export type CanvasNoteControllerDeleteNoteData = {
    path: {
        canvasId: string;
        noteId: string;
        roomId: string;
    };
};

export type CanvasNoteControllerDeleteNoteResponse = (unknown);

export type CanvasNoteControllerDeleteNoteError = unknown;

export type CanvasNoteControllerUpdateNoteData = {
    body: UpdateNoteRequestBodyDto;
    path: {
        canvasId: string;
        noteId: string;
        roomId: string;
    };
};

export type CanvasNoteControllerUpdateNoteResponse = (unknown);

export type CanvasNoteControllerUpdateNoteError = unknown;

export type CanvasDatabaseConnectionControllerGetStatsData = {
    path: {
        canvasId: string;
        databaseId: string;
        roomId: string;
    };
};

export type CanvasDatabaseConnectionControllerGetStatsResponse = (GetDatabaseStatsResponseBodyDto);

export type CanvasDatabaseConnectionControllerGetStatsError = unknown;

export type CanvasDatabaseConnectionControllerPerformSearchData = {
    body: PostSearchRequestBodyDto;
    path: {
        canvasId: string;
        databaseId: string;
        roomId: string;
    };
};

export type CanvasDatabaseConnectionControllerPerformSearchResponse = (PostSearchResponseBodyDto);

export type CanvasDatabaseConnectionControllerPerformSearchError = unknown;

export type CanvasDatabaseConnectionControllerGetSearchCapabilitesData = {
    path: {
        canvasId: string;
        databaseId: string;
        roomId: string;
    };
};

export type CanvasDatabaseConnectionControllerGetSearchCapabilitesResponse = (GetSearchCapabilitiesResponseBodyDto);

export type CanvasDatabaseConnectionControllerGetSearchCapabilitesError = unknown;

export type CanvasDatabaseConnectionControllerExpandNodePreviewData = {
    path: {
        canvasId: string;
        databaseId: string;
        roomId: string;
    };
    query: {
        nodeId: string;
    };
};

export type CanvasDatabaseConnectionControllerExpandNodePreviewResponse = (ExpandNodePreviewResponseBodyDto);

export type CanvasDatabaseConnectionControllerExpandNodePreviewError = unknown;

export type ActionControllerLoadScenarioData = {
    body: LoadScenarioRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerLoadScenarioResponse = (unknown);

export type ActionControllerLoadScenarioError = unknown;

export type ActionControllerReloadScenarioData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerReloadScenarioResponse = (unknown);

export type ActionControllerReloadScenarioError = unknown;

export type ActionControllerExpandNodeData = {
    body: ExpandNodeRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerExpandNodeResponse = (unknown);

export type ActionControllerExpandNodeError = unknown;

export type ActionControllerDeleteElementsData = {
    body: DeleteElementsRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerDeleteElementsResponse = (unknown);

export type ActionControllerDeleteElementsError = unknown;

export type ActionControllerRelayoutData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerRelayoutResponse = (unknown);

export type ActionControllerRelayoutError = unknown;

export type ActionControllerUnlockNodesData = {
    body: UnlockNodesRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerUnlockNodesResponse = (unknown);

export type ActionControllerUnlockNodesError = unknown;

export type ActionControllerFocusNodesData = {
    body: FocusNodesRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerFocusNodesResponse = (unknown);

export type ActionControllerFocusNodesError = unknown;

export type ActionControllerUndoData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerUndoResponse = (unknown);

export type ActionControllerUndoError = unknown;

export type ActionControllerRedoData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerRedoResponse = (unknown);

export type ActionControllerRedoError = unknown;

export type ActionControllerRunQueryData = {
    body: RunQueryRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerRunQueryResponse = (unknown);

export type ActionControllerRunQueryError = unknown;

export type ActionControllerConnectResultNodesData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerConnectResultNodesResponse = (unknown);

export type ActionControllerConnectResultNodesError = unknown;

export type ActionControllerUnlockAllNodesData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerUnlockAllNodesResponse = (unknown);

export type ActionControllerUnlockAllNodesError = unknown;

export type ActionControllerRemoveDanglingNodesData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerRemoveDanglingNodesResponse = (unknown);

export type ActionControllerRemoveDanglingNodesError = unknown;

export type ActionControllerCompressRelationshipsData = {
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerCompressRelationshipsResponse = (unknown);

export type ActionControllerCompressRelationshipsError = unknown;

export type ActionControllerCompressNodesData = {
    body: CompressNodesRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerCompressNodesResponse = (unknown);

export type ActionControllerCompressNodesError = unknown;

export type ActionControllerLayoutLabelData = {
    body: LayoutLabelRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerLayoutLabelResponse = (unknown);

export type ActionControllerLayoutLabelError = unknown;

export type ActionControllerShowShortestPathData = {
    body: ShowShortestPathRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerShowShortestPathResponse = (unknown);

export type ActionControllerShowShortestPathError = unknown;

export type ActionControllerLoadNodeData = {
    body: LoadNodeRequestBodyDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerLoadNodeResponse = (unknown);

export type ActionControllerLoadNodeError = unknown;

export type ActionControllerSetViewSettingsData = {
    body: LiveCanvasViewSettingsDto;
    path: {
        canvasId: string;
        roomId: string;
    };
};

export type ActionControllerSetViewSettingsResponse = (unknown);

export type ActionControllerSetViewSettingsError = unknown;

export type SystemControllerGetVersionResponse = (GetVersionResponseBodyDto);

export type SystemControllerGetVersionError = unknown;

export type RedirectControllerGetUrlData = {
    query: {
        url: string;
    };
};

export type RedirectControllerGetUrlResponse = (GetUrlResponseBodyDto);

export type RedirectControllerGetUrlError = unknown;