/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/scenario": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getScenarios"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scenario-group": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getScenarioGroups"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/database": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getDatabases"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRooms"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoom"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/version": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getVersion"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/backup": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getBackup"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/import": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postImport"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {integer} */
        readonly PresetColorIndex: 0 | 1 | 2 | 3 | 4 | 5;
        readonly PresetColor: {
            readonly index: components["schemas"]["PresetColorIndex"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "PresetColor";
        };
        readonly CustomColor: {
            readonly backgroundColor: string;
            readonly textColor: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "CustomColor";
        };
        readonly Color: components["schemas"]["PresetColor"] | components["schemas"]["CustomColor"];
        readonly GraphLabel: {
            readonly label: string;
            readonly color: components["schemas"]["Color"];
            readonly count: number;
            readonly sources: readonly string[];
        };
        readonly GraphProperty: {
            readonly slug: string;
            readonly value: components["schemas"]["GraphPropertyValue"];
        };
        readonly GraphPropertyValue: unknown;
        readonly Node: {
            readonly id: string;
            readonly title: string;
            readonly labels: readonly string[];
            readonly properties: readonly components["schemas"]["GraphProperty"][];
            readonly radius: number;
            readonly position: components["schemas"]["Position"];
            readonly inDegree: number;
            readonly outDegree: number;
            readonly degree: number;
            readonly namesInQuery: readonly string[];
            readonly displayConfigurationContext: unknown;
            readonly customBackgroundColor: string | null;
            readonly customTitleColor: string | null;
            readonly source: string;
            readonly additionalSources: readonly string[];
            readonly locked: boolean;
        };
        readonly PhysicalNode: {
            readonly id: string;
            readonly position: components["schemas"]["Position"];
        };
        readonly Position: {
            readonly x: number;
            readonly y: number;
        };
        readonly Edge: {
            readonly id: string;
            readonly startNodeId: string;
            readonly endNodeId: string;
            readonly type: string;
            readonly isLoop: boolean;
            readonly parallelCount: number;
            readonly parallelIndex: number;
            readonly compressedCount: number;
            readonly width: number;
            readonly properties: readonly components["schemas"]["GraphProperty"][];
            readonly namesInQuery: readonly string[];
            readonly source: string;
        };
        readonly ScenarioInfo: {
            readonly id: string;
            readonly title: string | null;
        } | null;
        readonly Histogram: {
            readonly nodeLabels: readonly {
                readonly label: string;
                readonly count: number;
                readonly percentage: number;
            }[];
            readonly nodeProperties: readonly {
                readonly key: string;
                readonly values: readonly {
                    readonly value: string;
                    readonly count: number;
                    readonly percentage: number;
                }[];
            }[];
            readonly edgeTypes: readonly {
                readonly type: string;
                readonly count: number;
                readonly percentage: number;
            }[];
            readonly edgeProperties: readonly {
                readonly key: string;
                readonly values: readonly {
                    readonly value: string;
                    readonly count: number;
                    readonly percentage: number;
                }[];
            }[];
        };
        readonly GraphMetaData: {
            readonly labels: readonly components["schemas"]["GraphLabel"][];
            readonly scenarioInfo: components["schemas"]["ScenarioInfo"];
            readonly pipelineSummary: readonly {
                readonly step: string;
                readonly durationMs: number;
            }[];
            readonly histogram: components["schemas"]["Histogram"];
        };
        readonly Graph: {
            readonly nodes: readonly components["schemas"]["Node"][];
            readonly edges: readonly components["schemas"]["Edge"][];
            readonly metaData: components["schemas"]["GraphMetaData"];
            readonly tableData: readonly {
                readonly [key: string]: unknown;
            }[];
        };
        readonly Room: {
            readonly id: string;
            readonly title: string | null;
        };
        readonly Rooms: {
            readonly rooms: readonly components["schemas"]["Room"][];
        };
        readonly Database: {
            readonly id: string;
            readonly title: string | null;
            readonly url: string | null;
            readonly browserUrl: string | null;
            readonly editUrl: string | null;
        };
        readonly Databases: {
            readonly databases: readonly components["schemas"]["Database"][];
        };
        readonly ScenarioGroup: {
            readonly id: string;
            readonly title: string | null;
            readonly editUrl: string | null;
        };
        readonly ScenarioGroups: {
            readonly scenarioGroups: readonly components["schemas"]["ScenarioGroup"][];
        };
        readonly Scenario: {
            readonly id: string;
            readonly title: string | null;
            readonly query: string | null;
            readonly description: string | null;
            /** Format: uri */
            readonly coverUrl: string | null;
            readonly editUrl: string | null;
        };
        readonly Scenarios: {
            readonly scenarios: readonly components["schemas"]["Scenario"][];
        };
        readonly Version: {
            readonly version: string;
        };
        readonly PhysicsPerformance: {
            /** @enum {string} */
            readonly performance: "good" | "bad";
            readonly loadPercent: number;
            readonly tickDuration: number;
        };
        readonly WSClientToServerMessage: components["schemas"]["WSActionJoinRoom"] | components["schemas"]["WSActionLoadScenario"] | components["schemas"]["WSActionGetGraph"] | components["schemas"]["WSActionGrabNode"] | components["schemas"]["WSActionMoveNodes"] | components["schemas"]["WSActionUngrabNode"] | components["schemas"]["WSActionExpandNodes"] | components["schemas"]["WSActionDeleteNodes"] | components["schemas"]["WSActionRelayout"] | components["schemas"]["WSActionUnlockNodes"];
        readonly WSServerToClientMessage: components["schemas"]["WSEventNodesMoved"] | components["schemas"]["WSEventRoomChanged"] | components["schemas"]["WSEventNotification"] | components["schemas"]["WSEventGraphChanged"] | components["schemas"]["WSEventProgress"] | components["schemas"]["WSEventClearProgress"] | components["schemas"]["WSEventSetLocks"] | components["schemas"]["WSEventLockUi"] | components["schemas"]["WSEventUnlockUi"] | components["schemas"]["WSEventPerformanceChanged"];
        readonly WSActionJoinRoom: {
            /** @enum {string} */
            readonly type: "WSActionJoinRoom";
            readonly roomId: string;
        };
        readonly WSActionLoadScenario: {
            /** @enum {string} */
            readonly type: "WSActionLoadScenario";
            readonly scenarioId: string;
        };
        readonly WSActionGetGraph: {
            /** @enum {string} */
            readonly type: "WSActionGetGraph";
        };
        readonly WSActionMoveNodes: {
            /** @enum {string} */
            readonly type: "WSActionMoveNodes";
            readonly nodes: readonly components["schemas"]["PhysicalNode"][];
        };
        readonly WSActionGrabNode: {
            /** @enum {string} */
            readonly type: "WSActionGrabNode";
            readonly nodeId: string;
        };
        readonly WSActionUngrabNode: {
            /** @enum {string} */
            readonly type: "WSActionUngrabNode";
            readonly node: components["schemas"]["PhysicalNode"];
        };
        readonly WSActionExpandNodes: {
            /** @enum {string} */
            readonly type: "WSActionExpandNodes";
            readonly nodes: readonly string[];
        };
        readonly WSActionDeleteNodes: {
            /** @enum {string} */
            readonly type: "WSActionDeleteNodes";
            readonly nodes: readonly string[];
        };
        readonly WSActionRelayout: {
            /** @enum {string} */
            readonly type: "WSActionRelayout";
        };
        readonly WSActionUnlockNodes: {
            /** @enum {string} */
            readonly type: "WSActionUnlockNodes";
            readonly nodes: readonly string[];
        };
        readonly WSEventGraphChanged: {
            /** @enum {string} */
            readonly type: "WSEventGraphChanged";
            readonly graph: components["schemas"]["Graph"];
        };
        readonly WSEventRoomChanged: {
            /** @enum {string} */
            readonly type: "WSEventRoomChanged";
            readonly roomId: string | null;
        };
        readonly WSEventNodesMoved: {
            /** @enum {string} */
            readonly type: "WSEventNodesMoved";
            readonly nodes: readonly components["schemas"]["PhysicalNode"][];
            /** Format: date */
            readonly date: string;
        };
        readonly WSEventNotification: {
            /** @enum {string} */
            readonly type: "WSEventNotification";
            readonly title: string;
            readonly message: string;
            /** @enum {string} */
            readonly severity: "error" | "message" | "warning";
            /** Format: date */
            readonly date: string;
        };
        readonly WSEventProgress: {
            /** @enum {string} */
            readonly type: "WSEventProgress";
            readonly progress: number | null;
            readonly message: string;
        };
        readonly WSEventClearProgress: {
            /** @enum {string} */
            readonly type: "WSEventClearProgress";
        };
        readonly WSEventSetLocks: {
            /** @enum {string} */
            readonly type: "WSEventSetLocks";
            readonly locks: readonly {
                readonly id: string;
                readonly locked: boolean;
            }[];
        };
        readonly WSEventLockUi: {
            /** @enum {string} */
            readonly type: "WSEventLockUi";
        };
        readonly WSEventUnlockUi: {
            /** @enum {string} */
            readonly type: "WSEventUnlockUi";
        };
        readonly WSEventPerformanceChanged: {
            /** @enum {string} */
            readonly type: "WSEventPerformanceChanged";
            readonly performance?: components["schemas"]["PhysicsPerformance"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaPresetColorIndex = components['schemas']['PresetColorIndex'];
export type SchemaPresetColor = components['schemas']['PresetColor'];
export type SchemaCustomColor = components['schemas']['CustomColor'];
export type SchemaColor = components['schemas']['Color'];
export type SchemaGraphLabel = components['schemas']['GraphLabel'];
export type SchemaGraphProperty = components['schemas']['GraphProperty'];
export type SchemaGraphPropertyValue = components['schemas']['GraphPropertyValue'];
export type SchemaNode = components['schemas']['Node'];
export type SchemaPhysicalNode = components['schemas']['PhysicalNode'];
export type SchemaPosition = components['schemas']['Position'];
export type SchemaEdge = components['schemas']['Edge'];
export type SchemaScenarioInfo = components['schemas']['ScenarioInfo'];
export type SchemaHistogram = components['schemas']['Histogram'];
export type SchemaGraphMetaData = components['schemas']['GraphMetaData'];
export type SchemaGraph = components['schemas']['Graph'];
export type SchemaRoom = components['schemas']['Room'];
export type SchemaRooms = components['schemas']['Rooms'];
export type SchemaDatabase = components['schemas']['Database'];
export type SchemaDatabases = components['schemas']['Databases'];
export type SchemaScenarioGroup = components['schemas']['ScenarioGroup'];
export type SchemaScenarioGroups = components['schemas']['ScenarioGroups'];
export type SchemaScenario = components['schemas']['Scenario'];
export type SchemaScenarios = components['schemas']['Scenarios'];
export type SchemaVersion = components['schemas']['Version'];
export type SchemaPhysicsPerformance = components['schemas']['PhysicsPerformance'];
export type SchemaWsClientToServerMessage = components['schemas']['WSClientToServerMessage'];
export type SchemaWsServerToClientMessage = components['schemas']['WSServerToClientMessage'];
export type SchemaWsActionJoinRoom = components['schemas']['WSActionJoinRoom'];
export type SchemaWsActionLoadScenario = components['schemas']['WSActionLoadScenario'];
export type SchemaWsActionGetGraph = components['schemas']['WSActionGetGraph'];
export type SchemaWsActionMoveNodes = components['schemas']['WSActionMoveNodes'];
export type SchemaWsActionGrabNode = components['schemas']['WSActionGrabNode'];
export type SchemaWsActionUngrabNode = components['schemas']['WSActionUngrabNode'];
export type SchemaWsActionExpandNodes = components['schemas']['WSActionExpandNodes'];
export type SchemaWsActionDeleteNodes = components['schemas']['WSActionDeleteNodes'];
export type SchemaWsActionRelayout = components['schemas']['WSActionRelayout'];
export type SchemaWsActionUnlockNodes = components['schemas']['WSActionUnlockNodes'];
export type SchemaWsEventGraphChanged = components['schemas']['WSEventGraphChanged'];
export type SchemaWsEventRoomChanged = components['schemas']['WSEventRoomChanged'];
export type SchemaWsEventNodesMoved = components['schemas']['WSEventNodesMoved'];
export type SchemaWsEventNotification = components['schemas']['WSEventNotification'];
export type SchemaWsEventProgress = components['schemas']['WSEventProgress'];
export type SchemaWsEventClearProgress = components['schemas']['WSEventClearProgress'];
export type SchemaWsEventSetLocks = components['schemas']['WSEventSetLocks'];
export type SchemaWsEventLockUi = components['schemas']['WSEventLockUi'];
export type SchemaWsEventUnlockUi = components['schemas']['WSEventUnlockUi'];
export type SchemaWsEventPerformanceChanged = components['schemas']['WSEventPerformanceChanged'];
export type $defs = Record<string, never>;
export interface operations {
    readonly getScenarios: {
        readonly parameters: {
            readonly query: {
                readonly scenarioGroupId: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Scenarios"];
                };
            };
        };
    };
    readonly getScenarioGroups: {
        readonly parameters: {
            readonly query: {
                readonly databaseId: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ScenarioGroups"];
                };
            };
        };
    };
    readonly getDatabases: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Databases"];
                };
            };
        };
    };
    readonly getRooms: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Rooms"];
                };
            };
        };
    };
    readonly getRoom: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    readonly getVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    readonly getBackup: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postImport: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to upload.
                     */
                    readonly file?: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
