/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/auth": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getAuth"];
        readonly put?: never;
        readonly post: operations["postAuth"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/start-page": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getStartPage"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/project-page/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getProjectPage"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas-page/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getCanvasPage"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["setCanvasData"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoom"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/scenarios": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoomScenarios"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/note": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postNote"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/note/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["putNote"];
        readonly post?: never;
        readonly delete: operations["deleteNote"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/graph": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getGraph"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/load-scenario": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionLoadScenario"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/reload-scenario": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionReloadScenario"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/expand-node": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionExpandNode"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/expand-node-preview": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionExpandNodePreview"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/delete-elements": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionDeleteElements"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/relayout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionRelayout"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/unlock-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionUnlockNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/focus-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionFocusNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/undo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionUndo"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/redo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionRedo"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/run-query": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionRunQuery"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/connect-result-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionConnectResultNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/unlock-all-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionUnlockAllNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/remove-dangling-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionRemoveDanglingNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/compress-relationships": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionCompressRelationships"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/compress-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionCompressNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/layout-label": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionLayoutLabel"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/show-shortest-path": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionShowShortestPath"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/canvas/{id}/actions/load-node": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postCanvasActionLoadNode"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/database/{id}/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getDatabaseStats"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/database/{id}/search": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postDatabaseSearch"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/database/{id}/search-capabilities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getDatabaseSearchCapabilities"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/version": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getVersion"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly GetScenariosResult: {
            readonly scenarioGroups: readonly components["schemas"]["ScenarioGroup"][];
            readonly parameterizedScenarios: readonly components["schemas"]["ScenarioGroup"][];
            readonly referencedDatabases: readonly components["schemas"]["DatabaseConnection"][];
        };
        /** @enum {integer} */
        readonly PresetColorIndex: 0 | 1 | 2 | 3 | 4 | 5;
        readonly PresetColor: {
            /** @enum {string} */
            readonly type: "PresetColor";
            readonly index: components["schemas"]["PresetColorIndex"];
        };
        readonly CustomColor: {
            /** @enum {string} */
            readonly type: "CustomColor";
            readonly backgroundColor: string;
            readonly textColor: string;
        };
        readonly Color: components["schemas"]["PresetColor"] | components["schemas"]["CustomColor"];
        readonly GraphLabel: {
            readonly label: string;
            readonly color: components["schemas"]["Color"];
            readonly count: number;
            readonly sources: readonly string[];
        };
        readonly GraphProperty: {
            readonly slug: string;
            readonly value: components["schemas"]["GraphPropertyValue"];
        };
        readonly GraphPropertyValue: unknown;
        /** @enum {string} */
        readonly CreationReason: "loadScenario" | "expand" | "query" | "merge" | "compress" | "connectResultNodes" | "search";
        readonly Node: {
            readonly id: string;
            readonly title: string;
            readonly labels: readonly string[];
            readonly nativeLabels: readonly string[];
            readonly properties: readonly components["schemas"]["GraphProperty"][];
            readonly radius: number;
            readonly position: components["schemas"]["Position"];
            readonly inDegree: number;
            readonly outDegree: number;
            readonly degree: number;
            readonly namesInQuery: readonly string[];
            readonly customColor: {
                readonly color: components["schemas"]["Color"];
            } | null;
            readonly customTitleColor?: string | null;
            readonly source: string;
            readonly locked: boolean;
            readonly isCluster: boolean;
            readonly clusterSize: number;
            readonly incomingEdges: readonly components["schemas"]["EdgePreview"][];
            readonly outgoingEdges: readonly components["schemas"]["EdgePreview"][];
            readonly creationReason: components["schemas"]["CreationReason"];
            readonly notes: readonly components["schemas"]["Note"][];
        };
        readonly PhysicalNode: {
            readonly id: string;
            readonly position: components["schemas"]["Position"];
        };
        readonly Position: {
            readonly x: number;
            readonly y: number;
        };
        readonly Edge: {
            readonly id: string;
            readonly startNodeId: string;
            readonly endNodeId: string;
            readonly type: string;
            readonly isLoop: boolean;
            readonly parallelCount: number;
            readonly parallelIndex: number;
            readonly isCluster: boolean;
            readonly width: number;
            readonly properties: readonly components["schemas"]["GraphProperty"][];
            readonly namesInQuery: readonly string[];
            readonly source: string;
            readonly clusterSize: number;
            readonly sourceNode: components["schemas"]["NodePreview"];
            readonly targetNode: components["schemas"]["NodePreview"];
            readonly creationReason: components["schemas"]["CreationReason"];
        };
        readonly NodePreview: {
            readonly id: string;
            readonly title: string;
            readonly labels: readonly string[];
            readonly customColor: {
                readonly color: components["schemas"]["Color"];
            } | null;
        };
        readonly EdgePreview: {
            readonly type: string;
            readonly count: number;
            readonly percentage: number;
        };
        readonly Histogram: {
            readonly nodeLabels: readonly {
                readonly label: string;
                readonly count: number;
                readonly percentage: number;
            }[];
            readonly nodeProperties: readonly {
                readonly key: string;
                readonly values: readonly {
                    readonly value: string;
                    readonly count: number;
                    readonly percentage: number;
                }[];
            }[];
            readonly edgeTypes: readonly {
                readonly type: string;
                readonly count: number;
                readonly percentage: number;
            }[];
            readonly edgeProperties: readonly {
                readonly key: string;
                readonly values: readonly {
                    readonly value: string;
                    readonly count: number;
                    readonly percentage: number;
                }[];
            }[];
            readonly nodes: readonly {
                readonly id: string;
                readonly title: string;
                readonly labels: readonly string[];
                readonly degree: number;
                readonly percentage: number;
                readonly customColor: {
                    readonly color: components["schemas"]["Color"];
                } | null;
            }[];
        };
        readonly GraphMetaData: {
            readonly scenario?: {
                readonly current: components["schemas"]["Scenario"];
            } | null;
            readonly arguments: readonly components["schemas"]["ScenarioArgument"][];
            readonly undoAction: string | null;
            readonly redoAction: string | null;
        };
        readonly GraphElements: {
            readonly nodes: readonly components["schemas"]["Node"][];
            readonly edges: readonly components["schemas"]["Edge"][];
            readonly labels: readonly components["schemas"]["GraphLabel"][];
            readonly histogram: components["schemas"]["Histogram"];
            readonly notes: readonly components["schemas"]["Note"][];
        };
        readonly GraphTable: {
            readonly data: readonly {
                readonly [key: string]: unknown;
            }[];
        };
        readonly Graph: {
            readonly elements: components["schemas"]["GraphElements"];
            readonly metaData: components["schemas"]["GraphMetaData"];
            readonly table: components["schemas"]["GraphTable"];
        };
        readonly Rooms: {
            readonly rooms: readonly components["schemas"]["Room"][];
        };
        readonly ScenarioQuery: {
            readonly query: string;
            readonly database: {
                readonly current: components["schemas"]["DatabaseConnection"];
            } | null;
        };
        readonly Scenario: {
            readonly id: string;
            readonly title: string | null;
            readonly queries: readonly components["schemas"]["ScenarioQuery"][];
            readonly description: string | null;
            readonly parameters: readonly components["schemas"]["ScenarioParameter"][];
            readonly additive?: boolean;
        };
        readonly ScenarioParameter: {
            readonly identifier: string;
            readonly title: string;
            readonly defaultValue: string | null;
            /** @enum {string} */
            readonly dataType: "string" | "number" | "json" | "startDateTime" | "endDateTime";
        };
        readonly ScenarioArgument: {
            readonly identifier: string;
            readonly value: string;
        };
        readonly Version: {
            readonly version: string;
        };
        readonly Notification: {
            readonly message: string;
            /** @enum {string} */
            readonly severity: "error" | "message" | "warning";
            /** Format: date */
            readonly date: string;
        };
        readonly PhysicsPerformance: {
            /** @enum {string} */
            readonly performance: "good" | "bad";
            readonly loadPercent: number;
            readonly tickDuration: number;
            readonly tickCount: number;
        };
        readonly ExpandNodePreviewElement: {
            readonly identificator: string;
            readonly count: number;
        };
        readonly DatabaseStats: {
            readonly relTypeCount: number;
            readonly labelCount: number;
            readonly relCount: number;
            readonly labels: readonly {
                readonly label: string;
                readonly exploreQuery: string;
            }[];
            readonly rels: readonly {
                readonly relType: string;
                readonly exploreQuery: string;
            }[];
            readonly nodeCount: number;
        };
        readonly DatabaseSearchCapabilities: {
            readonly canExactMatchElementId: boolean;
            readonly canExactMatchLabel: boolean;
            readonly exactMatchNodeProperties: readonly components["schemas"]["DatabaseSearchCapabilitiesEntry"][];
            readonly fuzzyMatchNodeProperties: readonly components["schemas"]["DatabaseSearchCapabilitiesEntry"][];
        };
        readonly DatabaseSearchCapabilitiesEntry: {
            readonly label: string;
            readonly property: string;
        };
        readonly Note: {
            readonly id: string;
            readonly content: string;
            readonly nodes: readonly components["schemas"]["NodePreview"][];
            readonly author: {
                readonly current: components["schemas"]["User"];
            } | null;
            /** Format: date-time */
            readonly dateTime: string;
            readonly color: {
                readonly color: components["schemas"]["Color"];
            } | null;
        };
        readonly LayoutSpecification: components["schemas"]["LayoutSpecificationForceDirected"] | components["schemas"]["LayoutSpecificationCircle"];
        readonly LayoutSpecificationForceDirected: {
            /** @enum {string} */
            readonly type: "LayoutSpecificationForceDirected";
        };
        readonly LayoutSpecificationCircle: {
            /** @enum {string} */
            readonly type: "LayoutSpecificationCircle";
            readonly radius: number;
        };
        readonly Projects: {
            readonly myProjects: readonly components["schemas"]["Project"][];
            readonly collaborationProjects: readonly components["schemas"]["Project"][];
        };
        readonly Project: {
            readonly id: string;
            readonly title: string;
            readonly owner: {
                readonly current: components["schemas"]["User"];
            } | null;
            readonly collaborators: readonly components["schemas"]["User"][];
            readonly databases: readonly components["schemas"]["DatabaseConnection"][];
            readonly scenarioGroups: readonly components["schemas"]["ScenarioGroup"][];
            readonly rooms: readonly components["schemas"]["Room"][];
        };
        /** @enum {string} */
        readonly ProjectRole: "owner" | "collaborator" | "none";
        readonly User: {
            readonly id: string;
            readonly displayName: string;
        };
        readonly DatabaseConnection: {
            readonly id: string;
            readonly title: string;
            readonly browserUrl: string;
            readonly connectionUrl: string;
        };
        readonly Room: {
            readonly id: string;
            readonly title: string;
            readonly visibility: components["schemas"]["RoomVisibility"];
            readonly canvases: readonly components["schemas"]["Canvas"][];
            readonly projectTitle: string;
        };
        /** @enum {string} */
        readonly RoomVisibility: "private" | "public" | "unlisted";
        readonly ScenarioGroup: {
            readonly id: string;
            readonly title: string;
            readonly scenarios: readonly components["schemas"]["Scenario"][];
        };
        readonly Canvas: {
            readonly id: string;
            readonly title: string;
            readonly roomId: string;
            readonly viewSettings: components["schemas"]["CanvasViewSettings"];
        };
        readonly StartPage: {
            readonly myProjects: readonly components["schemas"]["StartPageProject"][];
            readonly collaborationProjects: readonly components["schemas"]["StartPageProject"][];
            readonly recentRooms: readonly components["schemas"]["StartPageRoom"][];
            readonly publicRooms: readonly components["schemas"]["StartPageRoom"][];
        };
        readonly StartPageProject: {
            readonly id: string;
            readonly title: string;
            readonly owner: {
                readonly current: components["schemas"]["User"];
            } | null;
            readonly collaborators: readonly components["schemas"]["User"][];
            readonly databases: readonly components["schemas"]["DatabaseConnection"][];
        };
        readonly StartPageRoom: {
            readonly id: string;
            readonly title: string;
            readonly visibility: components["schemas"]["RoomVisibility"];
            readonly projectTitle: string;
        };
        readonly ProjectPage: {
            readonly id: string;
            readonly title: string;
            readonly owner: {
                readonly current: components["schemas"]["User"];
            } | null;
            readonly collaborators: readonly components["schemas"]["User"][];
            readonly databases: readonly components["schemas"]["DatabaseConnection"][];
            readonly scenarioGroups: readonly components["schemas"]["ScenarioGroup"][];
            readonly rooms: readonly components["schemas"]["Room"][];
        };
        readonly CanvasPage: {
            readonly canvas: components["schemas"]["Canvas"];
            readonly scenarios: components["schemas"]["GetScenariosResult"];
            readonly room: components["schemas"]["Room"];
        };
        readonly CanvasViewSettings: {
            readonly compressRelationshipsWidthFactor: number;
            readonly growNodesBasedOnDegree: boolean;
            readonly growNodesBasedOnDegreeFactor: number;
        };
        readonly WSClientToServerMessage: components["schemas"]["WSActionJoinCanvas"] | components["schemas"]["WSActionLeaveCanvas"] | components["schemas"]["WSActionGrabNode"] | components["schemas"]["WSActionMoveNodes"] | components["schemas"]["WSActionUngrabNode"];
        readonly WSServerToClientMessage: components["schemas"]["WSEventNodesMoved"] | components["schemas"]["WSEventCanvasChanged"] | components["schemas"]["WSEventNotification"] | components["schemas"]["WSEventGraphElementsChanged"] | components["schemas"]["WSEventGraphMetaDataChanged"] | components["schemas"]["WSEventGraphTableChanged"] | components["schemas"]["WSEventCanvasDataReady"] | components["schemas"]["WSEventProgress"] | components["schemas"]["WSEventClearProgress"] | components["schemas"]["WSEventSetNodeLocks"] | components["schemas"]["WSEventKick"];
        readonly WSActionJoinCanvas: {
            /** @enum {string} */
            readonly type: "WSActionJoinCanvas";
            readonly canvasId: string;
        };
        readonly WSActionLeaveCanvas: {
            /** @enum {string} */
            readonly type: "WSActionLeaveCanvas";
        };
        readonly WSActionMoveNodes: {
            /** @enum {string} */
            readonly type: "WSActionMoveNodes";
            readonly nodes: readonly components["schemas"]["PhysicalNode"][];
        };
        readonly WSActionGrabNode: {
            /** @enum {string} */
            readonly type: "WSActionGrabNode";
            readonly nodeId: string;
        };
        readonly WSActionUngrabNode: {
            /** @enum {string} */
            readonly type: "WSActionUngrabNode";
            readonly node: components["schemas"]["PhysicalNode"];
        };
        readonly WSEventGraphMetaDataChanged: {
            /** @enum {string} */
            readonly type: "WSEventGraphMetaDataChanged";
            readonly metaData: components["schemas"]["GraphMetaData"];
        };
        readonly WSEventGraphElementsChanged: {
            /** @enum {string} */
            readonly type: "WSEventGraphElementsChanged";
            readonly elements: components["schemas"]["GraphElements"];
        };
        readonly WSEventGraphTableChanged: {
            /** @enum {string} */
            readonly type: "WSEventGraphTableChanged";
            readonly table: components["schemas"]["GraphTable"];
        };
        readonly WSEventCanvasDataReady: {
            /** @enum {string} */
            readonly type: "WSEventCanvasDataReady";
            readonly metaData: components["schemas"]["GraphMetaData"];
            readonly elements: components["schemas"]["GraphElements"];
            readonly table: components["schemas"]["GraphTable"];
        };
        readonly WSEventCanvasChanged: {
            /** @enum {string} */
            readonly type: "WSEventCanvasChanged";
            readonly canvasId: string | null;
        };
        readonly WSEventNodesMoved: {
            /** @enum {string} */
            readonly type: "WSEventNodesMoved";
            readonly nodes: readonly components["schemas"]["PhysicalNode"][];
            /** Format: date */
            readonly date: string;
            readonly performance: components["schemas"]["PhysicsPerformance"];
        };
        readonly WSEventNotification: {
            /** @enum {string} */
            readonly type: "WSEventNotification";
            readonly notification: components["schemas"]["Notification"];
        };
        readonly WSEventProgress: {
            /** @enum {string} */
            readonly type: "WSEventProgress";
            readonly progress: number | null;
            readonly message: string;
        };
        readonly WSEventClearProgress: {
            /** @enum {string} */
            readonly type: "WSEventClearProgress";
        };
        readonly WSEventSetNodeLocks: {
            /** @enum {string} */
            readonly type: "WSEventSetNodeLocks";
            readonly locks: readonly {
                readonly id: string;
                readonly locked: boolean;
            }[];
        };
        readonly WSEventKick: {
            /** @enum {string} */
            readonly type: "WSEventKick";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaGetScenariosResult = components['schemas']['GetScenariosResult'];
export type SchemaPresetColorIndex = components['schemas']['PresetColorIndex'];
export type SchemaPresetColor = components['schemas']['PresetColor'];
export type SchemaCustomColor = components['schemas']['CustomColor'];
export type SchemaColor = components['schemas']['Color'];
export type SchemaGraphLabel = components['schemas']['GraphLabel'];
export type SchemaGraphProperty = components['schemas']['GraphProperty'];
export type SchemaGraphPropertyValue = components['schemas']['GraphPropertyValue'];
export type SchemaCreationReason = components['schemas']['CreationReason'];
export type SchemaNode = components['schemas']['Node'];
export type SchemaPhysicalNode = components['schemas']['PhysicalNode'];
export type SchemaPosition = components['schemas']['Position'];
export type SchemaEdge = components['schemas']['Edge'];
export type SchemaNodePreview = components['schemas']['NodePreview'];
export type SchemaEdgePreview = components['schemas']['EdgePreview'];
export type SchemaHistogram = components['schemas']['Histogram'];
export type SchemaGraphMetaData = components['schemas']['GraphMetaData'];
export type SchemaGraphElements = components['schemas']['GraphElements'];
export type SchemaGraphTable = components['schemas']['GraphTable'];
export type SchemaGraph = components['schemas']['Graph'];
export type SchemaRooms = components['schemas']['Rooms'];
export type SchemaScenarioQuery = components['schemas']['ScenarioQuery'];
export type SchemaScenario = components['schemas']['Scenario'];
export type SchemaScenarioParameter = components['schemas']['ScenarioParameter'];
export type SchemaScenarioArgument = components['schemas']['ScenarioArgument'];
export type SchemaVersion = components['schemas']['Version'];
export type SchemaNotification = components['schemas']['Notification'];
export type SchemaPhysicsPerformance = components['schemas']['PhysicsPerformance'];
export type SchemaExpandNodePreviewElement = components['schemas']['ExpandNodePreviewElement'];
export type SchemaDatabaseStats = components['schemas']['DatabaseStats'];
export type SchemaDatabaseSearchCapabilities = components['schemas']['DatabaseSearchCapabilities'];
export type SchemaDatabaseSearchCapabilitiesEntry = components['schemas']['DatabaseSearchCapabilitiesEntry'];
export type SchemaNote = components['schemas']['Note'];
export type SchemaLayoutSpecification = components['schemas']['LayoutSpecification'];
export type SchemaLayoutSpecificationForceDirected = components['schemas']['LayoutSpecificationForceDirected'];
export type SchemaLayoutSpecificationCircle = components['schemas']['LayoutSpecificationCircle'];
export type SchemaProjects = components['schemas']['Projects'];
export type SchemaProject = components['schemas']['Project'];
export type SchemaProjectRole = components['schemas']['ProjectRole'];
export type SchemaUser = components['schemas']['User'];
export type SchemaDatabaseConnection = components['schemas']['DatabaseConnection'];
export type SchemaRoom = components['schemas']['Room'];
export type SchemaRoomVisibility = components['schemas']['RoomVisibility'];
export type SchemaScenarioGroup = components['schemas']['ScenarioGroup'];
export type SchemaCanvas = components['schemas']['Canvas'];
export type SchemaStartPage = components['schemas']['StartPage'];
export type SchemaStartPageProject = components['schemas']['StartPageProject'];
export type SchemaStartPageRoom = components['schemas']['StartPageRoom'];
export type SchemaProjectPage = components['schemas']['ProjectPage'];
export type SchemaCanvasPage = components['schemas']['CanvasPage'];
export type SchemaCanvasViewSettings = components['schemas']['CanvasViewSettings'];
export type SchemaWsClientToServerMessage = components['schemas']['WSClientToServerMessage'];
export type SchemaWsServerToClientMessage = components['schemas']['WSServerToClientMessage'];
export type SchemaWsActionJoinCanvas = components['schemas']['WSActionJoinCanvas'];
export type SchemaWsActionLeaveCanvas = components['schemas']['WSActionLeaveCanvas'];
export type SchemaWsActionMoveNodes = components['schemas']['WSActionMoveNodes'];
export type SchemaWsActionGrabNode = components['schemas']['WSActionGrabNode'];
export type SchemaWsActionUngrabNode = components['schemas']['WSActionUngrabNode'];
export type SchemaWsEventGraphMetaDataChanged = components['schemas']['WSEventGraphMetaDataChanged'];
export type SchemaWsEventGraphElementsChanged = components['schemas']['WSEventGraphElementsChanged'];
export type SchemaWsEventGraphTableChanged = components['schemas']['WSEventGraphTableChanged'];
export type SchemaWsEventCanvasDataReady = components['schemas']['WSEventCanvasDataReady'];
export type SchemaWsEventCanvasChanged = components['schemas']['WSEventCanvasChanged'];
export type SchemaWsEventNodesMoved = components['schemas']['WSEventNodesMoved'];
export type SchemaWsEventNotification = components['schemas']['WSEventNotification'];
export type SchemaWsEventProgress = components['schemas']['WSEventProgress'];
export type SchemaWsEventClearProgress = components['schemas']['WSEventClearProgress'];
export type SchemaWsEventSetNodeLocks = components['schemas']['WSEventSetNodeLocks'];
export type SchemaWsEventKick = components['schemas']['WSEventKick'];
export type $defs = Record<string, never>;
export interface operations {
    readonly getAuth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly username: string;
                    };
                };
            };
        };
    };
    readonly postAuth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly username: string;
                    readonly password: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly jwt: string;
                        readonly username: string;
                    };
                };
            };
        };
    };
    readonly getStartPage: {
        readonly parameters: {
            readonly query: {
                readonly recentRoomIds: readonly string[];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StartPage"];
                };
            };
        };
    };
    readonly getProjectPage: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProjectPage"];
                };
            };
        };
    };
    readonly getCanvasPage: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CanvasPage"];
                };
            };
        };
    };
    readonly setCanvasData: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly viewSettings: components["schemas"]["CanvasViewSettings"];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Canvas"];
                };
            };
        };
    };
    readonly getRoom: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    readonly getRoomScenarios: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GetScenariosResult"];
                };
            };
        };
    };
    readonly postNote: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeIds: readonly string[];
                    readonly content: string;
                    readonly canvasId: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly putNote: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly content: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly deleteNote: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly getGraph: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Graph"];
                };
            };
        };
    };
    readonly postCanvasActionLoadScenario: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly scenarioId: string;
                    readonly additive: boolean;
                    readonly arguments: readonly components["schemas"]["ScenarioArgument"][];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionReloadScenario: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionExpandNode: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeIds: readonly string[];
                    readonly limit: {
                        readonly labels: readonly string[];
                        readonly relationships: readonly string[];
                    } | null;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionExpandNodePreview: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeId: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly relationships: readonly components["schemas"]["ExpandNodePreviewElement"][];
                        readonly labels: readonly components["schemas"]["ExpandNodePreviewElement"][];
                    } | null;
                };
            };
        };
    };
    readonly postCanvasActionDeleteElements: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodes: readonly string[];
                    readonly edges: readonly string[];
                    readonly labels: readonly string[];
                    readonly edgeTypes: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionRelayout: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionUnlockNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodes: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionFocusNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodes: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionUndo: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionRedo: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionRunQuery: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly databaseId: string;
                    readonly query: string;
                    readonly replace: boolean;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionConnectResultNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionUnlockAllNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionRemoveDanglingNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionCompressRelationships: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionCompressNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly label: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionLayoutLabel: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly label: string;
                    readonly layoutSpecification: components["schemas"]["LayoutSpecification"];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionShowShortestPath: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeIds: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postCanvasActionLoadNode: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeId: string;
                    readonly databaseId: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly getDatabaseStats: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DatabaseStats"];
                };
            };
        };
    };
    readonly postDatabaseSearch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly searchTerm: string;
                    readonly roomId: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly nodes: readonly components["schemas"]["NodePreview"][];
                    };
                };
            };
        };
    };
    readonly getDatabaseSearchCapabilities: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DatabaseSearchCapabilities"];
                };
            };
        };
    };
    readonly getVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
}
