/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/room/{id}/scenarios": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getScenarios"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRooms"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoom"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/graph": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoomGraph"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/graph/elements": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoomGraphElements"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/graph/meta-data": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoomGraphMetaData"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/graph/table": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getRoomGraphTable"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/notes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postNote"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/note/{noteId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["putNote"];
        readonly post?: never;
        readonly delete: operations["deleteNote"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/load-scenario": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionLoadScenario"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/reload-scenario": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionReloadScenario"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/expand-node": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionExpandNode"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/expand-node-preview": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionExpandNodePreview"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/delete-elements": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionDeleteElements"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/relayout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionRelayout"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/unlock-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionUnlockNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/focus-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionFocusNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/undo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionUndo"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/redo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionRedo"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/run-query": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionRunQuery"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/connect-result-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionConnectResultNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/unlock-all-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionUnlockAllNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/remove-dangling-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionRemoveDanglingNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/compress-relationships": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionCompressRelationships"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/compress-nodes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionCompressNodes"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/room/{id}/actions/layout-label": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postRoomActionLayoutLabel"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/database/{id}/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getDatabaseStats"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/version": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getVersion"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/backup": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getBackup"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/import": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postImport"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly GetScenariosResult: {
            readonly scenarioGroups: readonly components["schemas"]["ScenarioGroup"][];
            readonly parameterizedScenarios: readonly components["schemas"]["ScenarioGroup"][];
            readonly referencedDatabases: readonly components["schemas"]["Database"][];
        };
        /** @enum {integer} */
        readonly PresetColorIndex: 0 | 1 | 2 | 3 | 4 | 5;
        readonly PresetColor: {
            /** @enum {string} */
            readonly type: "PresetColor";
            readonly index: components["schemas"]["PresetColorIndex"];
        };
        readonly CustomColor: {
            /** @enum {string} */
            readonly type: "CustomColor";
            readonly backgroundColor: string;
            readonly textColor: string;
        };
        readonly Color: components["schemas"]["PresetColor"] | components["schemas"]["CustomColor"];
        readonly GraphLabel: {
            readonly label: string;
            readonly color: components["schemas"]["Color"];
            readonly count: number;
            readonly sources: readonly string[];
        };
        readonly GraphProperty: {
            readonly slug: string;
            readonly value: components["schemas"]["GraphPropertyValue"];
        };
        readonly GraphPropertyValue: unknown;
        /** @enum {string} */
        readonly CreationReason: "loadScenario" | "expand" | "query" | "merge" | "compress" | "connectResultNodes";
        readonly Node: {
            readonly id: string;
            readonly title: string;
            readonly labels: readonly string[];
            readonly nativeLabels: readonly string[];
            readonly properties: readonly components["schemas"]["GraphProperty"][];
            readonly radius: number;
            readonly position: components["schemas"]["Position"];
            readonly inDegree: number;
            readonly outDegree: number;
            readonly degree: number;
            readonly namesInQuery: readonly string[];
            readonly customColor: {
                readonly color: components["schemas"]["Color"];
            } | null;
            readonly customTitleColor?: string | null;
            readonly source: string;
            readonly locked: boolean;
            readonly isCluster: boolean;
            readonly clusterSize: number;
            readonly incomingEdges: readonly components["schemas"]["EdgePreview"][];
            readonly outgoingEdges: readonly components["schemas"]["EdgePreview"][];
            readonly creationReason: components["schemas"]["CreationReason"];
            readonly notes: readonly components["schemas"]["Note"][];
        };
        readonly PhysicalNode: {
            readonly id: string;
            readonly position: components["schemas"]["Position"];
        };
        readonly Position: {
            readonly x: number;
            readonly y: number;
        };
        readonly Edge: {
            readonly id: string;
            readonly startNodeId: string;
            readonly endNodeId: string;
            readonly type: string;
            readonly isLoop: boolean;
            readonly parallelCount: number;
            readonly parallelIndex: number;
            readonly isCluster: boolean;
            readonly width: number;
            readonly properties: readonly components["schemas"]["GraphProperty"][];
            readonly namesInQuery: readonly string[];
            readonly source: string;
            readonly clusterSize: number;
            readonly sourceNode: components["schemas"]["NodePreview"];
            readonly targetNode: components["schemas"]["NodePreview"];
            readonly creationReason: components["schemas"]["CreationReason"];
        };
        readonly NodePreview: {
            readonly id: string;
            readonly title: string;
            readonly labels: readonly string[];
            readonly customColor: {
                readonly color: components["schemas"]["Color"];
            } | null;
        };
        readonly EdgePreview: {
            readonly type: string;
            readonly count: number;
            readonly percentage: number;
        };
        readonly Histogram: {
            readonly nodeLabels: readonly {
                readonly label: string;
                readonly count: number;
                readonly percentage: number;
            }[];
            readonly nodeProperties: readonly {
                readonly key: string;
                readonly values: readonly {
                    readonly value: string;
                    readonly count: number;
                    readonly percentage: number;
                }[];
            }[];
            readonly edgeTypes: readonly {
                readonly type: string;
                readonly count: number;
                readonly percentage: number;
            }[];
            readonly edgeProperties: readonly {
                readonly key: string;
                readonly values: readonly {
                    readonly value: string;
                    readonly count: number;
                    readonly percentage: number;
                }[];
            }[];
            readonly nodes: readonly {
                readonly id: string;
                readonly title: string;
                readonly labels: readonly string[];
                readonly degree: number;
                readonly percentage: number;
                readonly customColor: {
                    readonly color: components["schemas"]["Color"];
                } | null;
            }[];
        };
        readonly GraphMetaData: {
            readonly scenario?: {
                readonly current: components["schemas"]["Scenario"];
            } | null;
            readonly pipelineSummary: readonly {
                readonly step: string;
                readonly durationMs: number;
            }[];
            readonly arguments: readonly components["schemas"]["ScenarioArgument"][];
            readonly canUndo: boolean;
            readonly canRedo: boolean;
        };
        readonly GraphElements: {
            readonly nodes: readonly components["schemas"]["Node"][];
            readonly edges: readonly components["schemas"]["Edge"][];
            readonly labels: readonly components["schemas"]["GraphLabel"][];
            readonly histogram: components["schemas"]["Histogram"];
            readonly notes: readonly components["schemas"]["Note"][];
        };
        readonly GraphTable: {
            readonly data: readonly {
                readonly [key: string]: unknown;
            }[];
        };
        readonly Graph: {
            readonly elements: components["schemas"]["GraphElements"];
            readonly metaData: components["schemas"]["GraphMetaData"];
            readonly table: components["schemas"]["GraphTable"];
        };
        readonly Room: {
            readonly id: string;
            readonly title: string | null;
            readonly scenario: {
                readonly current: components["schemas"]["Scenario"];
            } | null;
            readonly editUrl: string | null;
        };
        readonly Rooms: {
            readonly rooms: readonly components["schemas"]["Room"][];
        };
        readonly Database: {
            readonly id: string;
            readonly title: string | null;
            readonly url: string | null;
            readonly browserUrl: string | null;
            readonly editUrl: string | null;
        };
        readonly ScenarioGroup: {
            readonly id: string;
            readonly title: string | null;
            readonly editUrl: string | null;
            readonly scenarios: readonly components["schemas"]["Scenario"][];
        };
        readonly ScenarioQuery: {
            readonly query: string;
            readonly database: {
                readonly current: components["schemas"]["Database"];
            } | null;
        };
        readonly Scenario: {
            readonly id: string;
            readonly title: string | null;
            readonly queries: readonly components["schemas"]["ScenarioQuery"][];
            readonly description: string | null;
            /** Format: uri */
            readonly coverUrl: string | null;
            readonly editUrl: string | null;
            readonly parameters: readonly components["schemas"]["ScenarioParameter"][];
            readonly additive: boolean;
        };
        readonly ScenarioParameter: {
            readonly identifier: string;
            readonly title: string;
            readonly defaultValue: string | null;
        };
        readonly ScenarioArgument: {
            readonly identifier: string;
            readonly value: string;
        };
        readonly Version: {
            readonly version: string;
        };
        readonly Notification: {
            readonly message: string;
            /** @enum {string} */
            readonly severity: "error" | "message" | "warning";
            /** Format: date */
            readonly date: string;
        };
        readonly PhysicsPerformance: {
            /** @enum {string} */
            readonly performance: "good" | "bad";
            readonly loadPercent: number;
            readonly tickDuration: number;
        };
        readonly ExpandNodePreviewElement: {
            readonly identificator: string;
            readonly count: number;
        };
        readonly DatabaseStats: {
            readonly relTypeCount: number;
            readonly labelCount: number;
            readonly relCount: number;
            readonly labels: readonly {
                readonly label: string;
                readonly exploreQuery: string;
            }[];
            readonly rels: readonly {
                readonly relType: string;
                readonly exploreQuery: string;
            }[];
            readonly nodeCount: number;
        };
        readonly Note: {
            readonly id: string;
            readonly content: string;
            readonly nodes: readonly components["schemas"]["NodePreview"][];
            readonly author: string | null;
            /** Format: date-time */
            readonly dateTime: string;
            readonly color: {
                readonly color: components["schemas"]["Color"];
            } | null;
        };
        readonly LayoutSpecification: components["schemas"]["LayoutSpecificationForceDirected"] | components["schemas"]["LayoutSpecificationCircle"];
        readonly LayoutSpecificationForceDirected: {
            /** @enum {string} */
            readonly type: "LayoutSpecificationForceDirected";
        };
        readonly LayoutSpecificationCircle: {
            /** @enum {string} */
            readonly type: "LayoutSpecificationCircle";
            readonly radius: number;
        };
        readonly WSClientToServerMessage: components["schemas"]["WSActionJoinRoom"] | components["schemas"]["WSActionLeaveRoom"] | components["schemas"]["WSActionGrabNode"] | components["schemas"]["WSActionMoveNodes"] | components["schemas"]["WSActionUngrabNode"];
        readonly WSServerToClientMessage: components["schemas"]["WSEventNodesMoved"] | components["schemas"]["WSEventRoomChanged"] | components["schemas"]["WSEventNotification"] | components["schemas"]["WSEventGraphElementsChanged"] | components["schemas"]["WSEventGraphMetaDataChanged"] | components["schemas"]["WSEventGraphTableChanged"] | components["schemas"]["WSEventProgress"] | components["schemas"]["WSEventClearProgress"] | components["schemas"]["WSEventSetNodeLocks"] | components["schemas"]["WSEventLockUi"] | components["schemas"]["WSEventUnlockUi"] | components["schemas"]["WSEventPerformanceChanged"] | components["schemas"]["WSEventKick"];
        readonly WSActionJoinRoom: {
            /** @enum {string} */
            readonly type: "WSActionJoinRoom";
            readonly roomId: string;
        };
        readonly WSActionLeaveRoom: {
            /** @enum {string} */
            readonly type: "WSActionLeaveRoom";
        };
        readonly WSActionMoveNodes: {
            /** @enum {string} */
            readonly type: "WSActionMoveNodes";
            readonly nodes: readonly components["schemas"]["PhysicalNode"][];
        };
        readonly WSActionGrabNode: {
            /** @enum {string} */
            readonly type: "WSActionGrabNode";
            readonly nodeId: string;
        };
        readonly WSActionUngrabNode: {
            /** @enum {string} */
            readonly type: "WSActionUngrabNode";
            readonly node: components["schemas"]["PhysicalNode"];
        };
        readonly WSEventGraphMetaDataChanged: {
            /** @enum {string} */
            readonly type: "WSEventGraphMetaDataChanged";
            readonly metaData: components["schemas"]["GraphMetaData"];
        };
        readonly WSEventGraphElementsChanged: {
            /** @enum {string} */
            readonly type: "WSEventGraphElementsChanged";
            readonly elements: components["schemas"]["GraphElements"];
        };
        readonly WSEventGraphTableChanged: {
            /** @enum {string} */
            readonly type: "WSEventGraphTableChanged";
            readonly table: components["schemas"]["GraphTable"];
        };
        readonly WSEventRoomChanged: {
            /** @enum {string} */
            readonly type: "WSEventRoomChanged";
            readonly roomId: string | null;
        };
        readonly WSEventNodesMoved: {
            /** @enum {string} */
            readonly type: "WSEventNodesMoved";
            readonly nodes: readonly components["schemas"]["PhysicalNode"][];
            /** Format: date */
            readonly date: string;
        };
        readonly WSEventNotification: {
            /** @enum {string} */
            readonly type: "WSEventNotification";
            readonly notification: components["schemas"]["Notification"];
        };
        readonly WSEventProgress: {
            /** @enum {string} */
            readonly type: "WSEventProgress";
            readonly progress: number | null;
            readonly message: string;
        };
        readonly WSEventClearProgress: {
            /** @enum {string} */
            readonly type: "WSEventClearProgress";
        };
        readonly WSEventSetNodeLocks: {
            /** @enum {string} */
            readonly type: "WSEventSetNodeLocks";
            readonly locks: readonly {
                readonly id: string;
                readonly locked: boolean;
            }[];
        };
        readonly WSEventLockUi: {
            /** @enum {string} */
            readonly type: "WSEventLockUi";
        };
        readonly WSEventUnlockUi: {
            /** @enum {string} */
            readonly type: "WSEventUnlockUi";
        };
        readonly WSEventPerformanceChanged: {
            /** @enum {string} */
            readonly type: "WSEventPerformanceChanged";
            readonly performance?: components["schemas"]["PhysicsPerformance"];
        };
        readonly WSEventKick: {
            /** @enum {string} */
            readonly type: "WSEventKick";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaGetScenariosResult = components['schemas']['GetScenariosResult'];
export type SchemaPresetColorIndex = components['schemas']['PresetColorIndex'];
export type SchemaPresetColor = components['schemas']['PresetColor'];
export type SchemaCustomColor = components['schemas']['CustomColor'];
export type SchemaColor = components['schemas']['Color'];
export type SchemaGraphLabel = components['schemas']['GraphLabel'];
export type SchemaGraphProperty = components['schemas']['GraphProperty'];
export type SchemaGraphPropertyValue = components['schemas']['GraphPropertyValue'];
export type SchemaCreationReason = components['schemas']['CreationReason'];
export type SchemaNode = components['schemas']['Node'];
export type SchemaPhysicalNode = components['schemas']['PhysicalNode'];
export type SchemaPosition = components['schemas']['Position'];
export type SchemaEdge = components['schemas']['Edge'];
export type SchemaNodePreview = components['schemas']['NodePreview'];
export type SchemaEdgePreview = components['schemas']['EdgePreview'];
export type SchemaHistogram = components['schemas']['Histogram'];
export type SchemaGraphMetaData = components['schemas']['GraphMetaData'];
export type SchemaGraphElements = components['schemas']['GraphElements'];
export type SchemaGraphTable = components['schemas']['GraphTable'];
export type SchemaGraph = components['schemas']['Graph'];
export type SchemaRoom = components['schemas']['Room'];
export type SchemaRooms = components['schemas']['Rooms'];
export type SchemaDatabase = components['schemas']['Database'];
export type SchemaScenarioGroup = components['schemas']['ScenarioGroup'];
export type SchemaScenarioQuery = components['schemas']['ScenarioQuery'];
export type SchemaScenario = components['schemas']['Scenario'];
export type SchemaScenarioParameter = components['schemas']['ScenarioParameter'];
export type SchemaScenarioArgument = components['schemas']['ScenarioArgument'];
export type SchemaVersion = components['schemas']['Version'];
export type SchemaNotification = components['schemas']['Notification'];
export type SchemaPhysicsPerformance = components['schemas']['PhysicsPerformance'];
export type SchemaExpandNodePreviewElement = components['schemas']['ExpandNodePreviewElement'];
export type SchemaDatabaseStats = components['schemas']['DatabaseStats'];
export type SchemaNote = components['schemas']['Note'];
export type SchemaLayoutSpecification = components['schemas']['LayoutSpecification'];
export type SchemaLayoutSpecificationForceDirected = components['schemas']['LayoutSpecificationForceDirected'];
export type SchemaLayoutSpecificationCircle = components['schemas']['LayoutSpecificationCircle'];
export type SchemaWsClientToServerMessage = components['schemas']['WSClientToServerMessage'];
export type SchemaWsServerToClientMessage = components['schemas']['WSServerToClientMessage'];
export type SchemaWsActionJoinRoom = components['schemas']['WSActionJoinRoom'];
export type SchemaWsActionLeaveRoom = components['schemas']['WSActionLeaveRoom'];
export type SchemaWsActionMoveNodes = components['schemas']['WSActionMoveNodes'];
export type SchemaWsActionGrabNode = components['schemas']['WSActionGrabNode'];
export type SchemaWsActionUngrabNode = components['schemas']['WSActionUngrabNode'];
export type SchemaWsEventGraphMetaDataChanged = components['schemas']['WSEventGraphMetaDataChanged'];
export type SchemaWsEventGraphElementsChanged = components['schemas']['WSEventGraphElementsChanged'];
export type SchemaWsEventGraphTableChanged = components['schemas']['WSEventGraphTableChanged'];
export type SchemaWsEventRoomChanged = components['schemas']['WSEventRoomChanged'];
export type SchemaWsEventNodesMoved = components['schemas']['WSEventNodesMoved'];
export type SchemaWsEventNotification = components['schemas']['WSEventNotification'];
export type SchemaWsEventProgress = components['schemas']['WSEventProgress'];
export type SchemaWsEventClearProgress = components['schemas']['WSEventClearProgress'];
export type SchemaWsEventSetNodeLocks = components['schemas']['WSEventSetNodeLocks'];
export type SchemaWsEventLockUi = components['schemas']['WSEventLockUi'];
export type SchemaWsEventUnlockUi = components['schemas']['WSEventUnlockUi'];
export type SchemaWsEventPerformanceChanged = components['schemas']['WSEventPerformanceChanged'];
export type SchemaWsEventKick = components['schemas']['WSEventKick'];
export type $defs = Record<string, never>;
export interface operations {
    readonly getScenarios: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GetScenariosResult"];
                };
            };
        };
    };
    readonly getRooms: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Rooms"];
                };
            };
        };
    };
    readonly getRoom: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Room"];
                };
            };
        };
    };
    readonly getRoomGraph: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Graph"];
                };
            };
        };
    };
    readonly getRoomGraphElements: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GraphElements"];
                };
            };
        };
    };
    readonly getRoomGraphMetaData: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GraphMetaData"];
                };
            };
        };
    };
    readonly getRoomGraphTable: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GraphTable"];
                };
            };
        };
    };
    readonly postNote: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeIds: readonly string[];
                    readonly content: string;
                    readonly color: {
                        readonly color: components["schemas"]["Color"];
                    } | null;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly putNote: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
                readonly noteId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeIds: readonly string[];
                    readonly content: string;
                    readonly color: {
                        readonly color: components["schemas"]["Color"];
                    } | null;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly deleteNote: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
                readonly noteId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionLoadScenario: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly scenarioId: string;
                    readonly arguments: readonly components["schemas"]["ScenarioArgument"][];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionReloadScenario: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionExpandNode: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeId: string;
                    readonly limit: {
                        readonly labels: readonly string[];
                        readonly relationships: readonly string[];
                    };
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionExpandNodePreview: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodeId: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly relationships: readonly components["schemas"]["ExpandNodePreviewElement"][];
                        readonly labels: readonly components["schemas"]["ExpandNodePreviewElement"][];
                    } | null;
                };
            };
        };
    };
    readonly postRoomActionDeleteElements: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodes: readonly string[];
                    readonly edges: readonly string[];
                    readonly labels: readonly string[];
                    readonly edgeTypes: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionRelayout: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionUnlockNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodes: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionFocusNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly nodes: readonly string[];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionUndo: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionRedo: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionRunQuery: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly databaseId: string;
                    readonly query: string;
                    readonly replace: boolean;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionConnectResultNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionUnlockAllNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionRemoveDanglingNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionCompressRelationships: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionCompressNodes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly label: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postRoomActionLayoutLabel: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly label: string;
                    readonly layoutSpecification: components["schemas"]["LayoutSpecification"];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly getDatabaseStats: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DatabaseStats"];
                };
            };
        };
    };
    readonly getVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    readonly getBackup: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly postImport: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to upload.
                     */
                    readonly file?: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
