ci_nakar-server:
  stage: ci_build
  tags:
    - docker
  cache:
    paths:
      - nakar-server/node_modules/
  before_script:
    - cd nakar-shared
    - npm ci
    - npm run build
    - cd ..
    - cd nakar-server
    - npm ci
  script:
    - npm run build:gen
    - npm run build
    - docker build -t "nakar-server:dev" .
    - npm run lint
    - npm run audit

deploy_nakar-server:
  stage: build_push_docker
  only:
    - prod
  tags:
    - docker
  cache:
    paths:
      - nakar-server/node_modules/
  before_script:
    - cd nakar-shared
    - npm ci
    - npm run build
    - cd ..
    - cd nakar-server
  script:
    - docker build -t "git-registry.thm.de/sspp77/nakar/server:$(npm run --silent version)" .
    - docker push git-registry.thm.de/sspp77/nakar/server:$(npm run --silent version)
