ci_server:
  stage: ci_build
  tags:
    - nodejs
  cache:
    paths:
      - nakar-server/node_modules
  before_script:
    - cd nakar-server
    - npm ci
  script:
    - npm run build
    - npm run lint
    - npm run audit

ci_server_docker:
  stage: ci_build
  tags:
    - docker
  script:
    - docker build -f nakar-server/Dockerfile -t "nakar-server:dev" .
  after_script:
    - docker rmi "nakar-server:dev"

deploy_server:
  stage: build_push_docker
  only:
    - prod
  tags:
    - docker
  script:
    - IMAGE_VERSION=$(cd nakar-server && npm run --silent version)
    - docker build -f nakar-server/Dockerfile -t "git-registry.thm.de/sspp77/nakar/server:$IMAGE_VERSION" .
    - docker push "git-registry.thm.de/sspp77/nakar/server:$IMAGE_VERSION"
    - docker rmi "git-registry.thm.de/sspp77/nakar/server:$IMAGE_VERSION"
