name: CI

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  ci-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: ./nakar-server/package-lock.json
      - name: Install
        run: |
          cd nakar-server
          npm ci
      - name: Build
        run: |
          cd nakar-server
          npm run build
      - name: Test
        run: |
          cd nakar-server
          npm run test
      - name: Lint
        run: |
          cd nakar-server
          npm run lint
      - name: Format
        run: |
          cd nakar-server
          npm run format
      - name: Analysis
        run: |
          cd nakar-server
          npm run analyze
      - name: Audit
        run: |
          cd nakar-server
          npm run audit || true
      - name: Import Demo Data
        run: |
          cd nakar-server
          cp .env.example .env
          node_modules/.bin/strapi import --force --file examples/export.tar

  ci-server-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-server
          push: false
          tags: ghcr.io/thm-graphs/nakar/server:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ci-client-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: ./nakar-client-web/package-lock.json
      - name: Install
        run: |
          cd nakar-client-web
          npm ci
      - name: Build
        run: |
          cd nakar-client-web
          npm run build
      - name: Lint
        run: |
          cd nakar-client-web
          npm run lint
      - name: Format
        run: |
          cd nakar-client-web
          npm run format
      - name: Analysis
        run: |
          cd nakar-client-web
          npm run analyze
      - name: Audit
        run: |
          cd nakar-client-web
          npm run audit

  ci-client-web-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-client-web
          push: false
          tags: ghcr.io/thm-graphs/nakar/client-web:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ci-nakar-db-pole:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-db-pole
          push: false
          tags: ghcr.io/thm-graphs/nakar/db-pole:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ci-nakar-db-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build
        run: |
          cd nakar-db-examples
          docker buildx ls
          npm run build:docker
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-db-examples
          push: false
          tags: ghcr.io/thm-graphs/nakar/db-examples:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
