# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

env:
  NODE_VERSION: "22.x"
  OS_VERSION: "ubuntu-24.04"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-nakar-db-pole:
    runs-on: ${{ env.OS_VERSION }}
    defaults:
      run:
        working-directory: nakar-db-pole
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run build
    
  build-nakar-server:
    runs-on: ${{ env.OS_VERSION }}
    defaults:
      run:
        working-directory: nakar-server
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run audit
    
  build-nakar-client-web:
    runs-on: ${{ env.OS_VERSION }}
    defaults:
      run:
        working-directory: nakar-client-web
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run audit
