name: CI

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  ci-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: ./nakar-server/package-lock.json
      - name: Install
        run: |
          cd nakar-server
          npm ci
      - name: Analysis
        run: |
          cd nakar-server
          npm run lint
          npm run format
      - name: Build
        run: |
          cd nakar-server
          npm run build

  ci-server-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-server
          push: false
          tags: ghcr.io/thm-graphs/nakar/server:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ci-client-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: ./nakar-client-web/package-lock.json
      - name: Install api-client
        run: |
          cd nakar-client-web/packages/api-client
          npm ci
          npm run build
      - name: Install
        run: |
          cd nakar-client-web
          npm ci
      - name: Analysis
        run: |
          cd nakar-client-web
          npm run lint
          npm run format
      - name: Build
        run: |
          cd nakar-client-web
          npm run build

  ci-client-web-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-client-web
          push: false
          tags: ghcr.io/thm-graphs/nakar/client-web:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ci-nakar-db-pole:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-db-pole
          push: false
          tags: ghcr.io/thm-graphs/nakar/db-pole:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ci-nakar-db-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Build
        run: |
          cd nakar-db-examples
          docker buildx ls
          npm run build:docker
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: ./nakar-db-examples
          push: false
          tags: ghcr.io/thm-graphs/nakar/db-examples:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ci-client-vision:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v6
  #     - name: Set up Xcode
  #       run: sudo xcode-select -s /Applications/Xcode_16.2.app
  #     - name: Build
  #       run: |
  #         cd nakar-client-vision
  #         xcodebuild -scheme "nakar-client-vision" -sdk xros -skipPackagePluginValidation CODE_SIGNING_ALLOWED="NO"
