name: CI

on:
  push:
    branches:
      - "**"

jobs:
  ci-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install
        run: |
          cd nakar-server
          npm ci
      - name: Build
        run: |
          cd nakar-server
          npm run build
          npm run build:docker
      - name: Analysis
        run: |
          cd nakar-server
          npm run lint

  ci-client-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install
        run: |
          cd nakar-client-web
          npm ci
      - name: Build
        run: |
          cd nakar-client-web
          npm run build
          npm run build:docker
      - name: Analysis
        run: |
          cd nakar-client-web
          npm run lint

  ci-nakar-db-pole:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd nakar-db-pole
          npm run build:docker

  ci-client-vision:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Build
        run: |
          cd nakar-client-vision
          xcodebuild -scheme "nakar-client-vision" -sdk xros -skipPackagePluginValidation CODE_SIGNING_ALLOWED="NO"
