# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

env:
  NODE_VERSION_1: 22.x

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-nakar-db-pole:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nakar-db-pole
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run build
    
  build-nakar-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{NODE_VERSION}}
    defaults:
      run:
        working-directory: nakar-server
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run audit
    
  build-nakar-client-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{NODE_VERSION}}
    defaults:
      run:
        working-directory: nakar-client-web
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run audit
